/* 考研词汇 — 词库浏览、多选与 AI 多词造句。 */
(function () {
  'use strict';
  var WORDS = [], filtered = [], shown = 0, PAGE = 48;
  var activeFilter='all', activeLetter='', searchQ='', dataFilters={};
  var selected = {};
  var listEl=document.getElementById('catalog-list'), countPill=document.getElementById('count-pill'), filterInput=document.getElementById('filter-input'), filterChips=document.getElementById('filter-chips'), dataFilterChips=document.getElementById('data-filter-chips'), letterIndex=document.getElementById('letter-index'), loadMore=document.getElementById('load-more'), loadMoreBtn=document.getElementById('load-more-btn'), descEl=document.getElementById('catalog-desc');
  var panel=document.getElementById('selection-panel'), selectedCount=document.getElementById('selected-count'), selectedWords=document.getElementById('selected-words'), multiBtn=document.getElementById('multi-ai-btn'), clearBtn=document.getElementById('clear-selected'), selectVisibleBtn=document.getElementById('select-visible'), modal=document.getElementById('multi-modal'), resultEl=document.getElementById('multi-result'), subtitle=document.getElementById('multi-subtitle'), copyBtn=document.getElementById('multi-copy'), againBtn=document.getElementById('multi-again');

  var xhr=new XMLHttpRequest(); xhr.open('GET','data/words.json',true); xhr.onload=function(){
    if(xhr.status!==200){listEl.textContent='词库加载失败';return;}
    WORDS=JSON.parse(xhr.responseText).words||[]; WORDS.sort(function(a,b){return a.word.localeCompare(b.word);});
    descEl.textContent='英语一主词库 '+WORDS.filter(function(w){return w.active!==false;}).length+' 词；全部词条含本地释义，可按数据完整度组合筛选。可多选单词，让 AI 把它们放进同一个考研英语句子。';
    buildLetterIndex(); applyFilters();
  }; xhr.send();

  function buildLetterIndex(){var present={}; WORDS.forEach(function(w){present[(w.word[0]||'#').toUpperCase()]=true;}); letterIndex.innerHTML='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(function(L){var has=!!present[L];return '<button type="button" class="'+(has?'':'empty')+'" data-letter="'+L+'"'+(has?'':' disabled')+'>'+L+'</button>';}).join('');}
  letterIndex.addEventListener('click',function(e){var b=e.target.closest('button[data-letter]');if(!b||b.disabled)return;var L=b.getAttribute('data-letter');activeLetter=activeLetter===L?'':L;letterIndex.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-letter')===activeLetter);});applyFilters();});
  filterChips.addEventListener('click',function(e){var c=e.target.closest('.filter-chip');if(!c)return;activeFilter=c.getAttribute('data-filter');filterChips.querySelectorAll('.filter-chip').forEach(function(x){x.classList.toggle('active',x===c);});applyFilters();});
  dataFilterChips.addEventListener('click',function(e){var c=e.target.closest('.filter-chip');if(!c)return;var k=c.getAttribute('data-filter');if(k==='all'){dataFilters={};dataFilterChips.querySelectorAll('.filter-chip').forEach(function(x){x.classList.toggle('active',x===c);});}else{dataFilterChips.querySelector('[data-filter="all"]').classList.remove('active');dataFilters[k]=!dataFilters[k];c.classList.toggle('active',dataFilters[k]);}applyFilters();});
  var debounce; filterInput.addEventListener('input',function(){clearTimeout(debounce);debounce=setTimeout(function(){searchQ=filterInput.value.trim().toLowerCase();applyFilters();},120);});

  function hasData(w,k){switch(k){case 'exam':return !!w.exam_meaning;case 'secondary':return !!(w.secondary_meanings&&w.secondary_meanings.length);case 'collocation':return !!w.collocation_hint;case 'example':return !!w.example_en;case 'family':return !!w.word_family;case 'phonetic':return !!w.phonetic;case 'pos':return !!w.pos;case 'forms':return !!(w.word_forms&&w.word_forms.length);}return true;}

  function applyFilters(){var keys=Object.keys(dataFilters).filter(function(k){return dataFilters[k];});filtered=WORDS.filter(function(w){if(w.active===false)return false;if(activeFilter!=='all'&&w.tier!==activeFilter)return false;if(activeLetter&&w.word[0].toUpperCase()!==activeLetter)return false;for(var i=0;i<keys.length;i++){if(!hasData(w,keys[i]))return false;}var tr=String(w.translation||'').toLowerCase();return !searchQ||(w.word.indexOf(searchQ)>-1||tr.indexOf(searchQ)>-1);});shown=0;listEl.innerHTML='';renderPage();countPill.textContent='显示 '+filtered.length+' 词';}
  function renderPage(){var frag=document.createDocumentFragment(),end=Math.min(shown+PAGE,filtered.length);for(var i=shown;i<end;i++){var w=filtered[i],wrap=document.createElement('div');wrap.className='cat-card-wrap';var checked=!!selected[w.word];wrap.innerHTML='<label class="word-check"><input type="checkbox" data-select-word="'+esc(w.word)+'" '+(checked?'checked':'')+' aria-label="选择 '+esc(w.word)+'"><span></span></label><a class="cat-card" href="search.html?w='+encodeURIComponent(w.word)+'"><div><span class="cw">'+esc(w.word)+'</span>'+(w.phonetic?'<span class="cp">'+esc(w.phonetic)+'</span>':'')+'</div><div class="cz">'+esc(w.exam_meaning||w.translation||'点击查词获取释义')+'</div><div class="ct">'+esc(w.tier||'')+' · '+esc(w.true_priority||'')+'</div></a>';frag.appendChild(wrap);}listEl.appendChild(frag);shown=end;loadMore.hidden=shown>=filtered.length;loadMoreBtn.textContent='加载更多（剩余 '+Math.max(0,filtered.length-shown)+'）';if(!filtered.length)listEl.innerHTML='<div class="catalog-empty">没有符合条件的单词</div>';}
  loadMoreBtn.addEventListener('click',renderPage);
  listEl.addEventListener('change',function(e){var cb=e.target.closest('input[data-select-word]');if(!cb)return;var word=cb.getAttribute('data-select-word');if(cb.checked){if(Object.keys(selected).length>=8){cb.checked=false;alert('最多选择 8 个单词。');return;}selected[word]=WORDS.find(function(w){return w.word===word;})||{word:word};}else delete selected[word];updateSelection();});
  selectVisibleBtn.addEventListener('click',function(){var pageWords=filtered.slice(0,shown),added=0;pageWords.forEach(function(w){if(!selected[w.word]&&Object.keys(selected).length<8){selected[w.word]=w;added++;}});updateSelection();renderPage();if(!added&&Object.keys(selected).length>=8)alert('最多选择 8 个单词。');});
  clearBtn.addEventListener('click',function(){selected={};updateSelection();applyFilters();});
  function updateSelection(){var arr=Object.keys(selected).map(function(k){return selected[k];});selectedCount.textContent=arr.length;panel.hidden=arr.length===0;multiBtn.disabled=arr.length<2;selectedWords.innerHTML=arr.map(function(w){return '<button type="button" class="selected-chip" data-remove-selected="'+esc(w.word)+'">'+esc(w.word)+' ×</button>';}).join('');}
  selectedWords.addEventListener('click',function(e){var b=e.target.closest('[data-remove-selected]');if(!b)return;delete selected[b.getAttribute('data-remove-selected')];updateSelection();applyFilters();});

  function openModal(){var arr=Object.keys(selected).map(function(k){return selected[k];});if(arr.length<2)return;modal.hidden=false;modal.setAttribute('aria-hidden','false');modal.removeAttribute('inert');subtitle.textContent=arr.map(function(x){return x.word;}).join(' · ');resultEl.innerHTML='<p class="ai-empty"><span class="spinner" style="width:16px;height:16px;display:inline-block;vertical-align:middle"></span> 正在生成一条把所有单词自然串起来的考研英语句子…</p>';generate(arr);}
  function closeModal(){modal.hidden=true;modal.setAttribute('aria-hidden','true');modal.setAttribute('inert','');}
  multiBtn.addEventListener('click',openModal);againBtn.addEventListener('click',function(){generate(Object.keys(selected).map(function(k){return selected[k];}));});
  document.addEventListener('click',function(e){if(e.target.closest('[data-multi-close]'))closeModal();}); document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!modal.hidden)closeModal();});
  function generate(arr){againBtn.disabled=true; if(!window.KaoyanAI){resultEl.innerHTML='<p class="ai-empty">AI 模块未加载，请刷新页面。</p>';againBtn.disabled=false;return;} window.KaoyanAI.generateMulti(arr).then(function(o){resultEl.innerHTML='<p class="example-en">'+highlight(o.sentence,arr.map(function(x){return x.word;}))+'</p><p class="example-zh">'+esc(o.translation)+'</p>'+(o.topic?'<p class="ai-meta"><b>语境：</b>'+esc(o.topic)+'</p>':'')+(o.structure?'<p class="ai-meta"><b>结构：</b>'+esc(o.structure)+'</p>':'')+(o.vocabulary?'<p class="ai-meta"><b>重点：</b>'+esc(o.vocabulary)+'</p>':'');}).catch(function(e){resultEl.innerHTML='<p class="ai-empty">生成失败：'+esc(String(e.message||e))+'。请先在查词页的「AI 设置」中配置 DeepSeek。</p>';}).finally(function(){againBtn.disabled=false;});}
  copyBtn.addEventListener('click',function(){var en=resultEl.querySelector('.example-en');if(!en)return;navigator.clipboard&&navigator.clipboard.writeText(en.innerText).then(function(){copyBtn.textContent='已复制 ✓';setTimeout(function(){copyBtn.textContent='复制句子';},1200);});});
  function highlight(sentence,words){var out=esc(sentence);words.sort(function(a,b){return b.length-a.length;}).forEach(function(w){var re=new RegExp('\\b('+escReg(w)+'(?:s|es|ed|ing)?\\b)','gi');out=out.replace(re,'<span class="hl">$1</span>');});return out;}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});} function escReg(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
})();