# -*- coding: utf-8 -*-
"""
High-Precision Linguistic Etymology & Morphology Master Engine
Accurately decomposes 5894 Kaoyan active words with strict morphological boundary checking.
"""

import json, os, sys, re

sys.stdout.reconfigure(encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, 'data')
WORDS_PATH = os.path.join(DATA_DIR, 'words.json')

# 1. Compound words & High-Frequency Academic Words Dictionary
SPECIAL_ROOTS = {
    'actively': 'act/ag (行动、做、驱动) + -ive (形容词后缀) + -ly (副词后缀) → 积极地、活跃地',
    'active': 'act/ag (行动、做、驱动) + -ive (形容词后缀) → 积极的、活跃的',
    'action': 'act/ag (行动、做、驱动) + -ion (名词后缀) → 行动、作为、诉讼',
    'activity': 'act/ag (行动、做、驱动) + -ivity (名词后缀) → 活动、活力',
    'actor': 'act/ag (行动、做、驱动) + -or (人) → 演员、行动者',
    'act': 'act/ag (行动、做、驱动) → 行动、法案、表现',
    'react': 're- (反、回) + act/ag (行动、做) → 反应、起反作用',
    'transaction': 'trans- (穿过、跨越) + act/ag (做、交易) + -ion → 业务、交易',
    'partisan': 'part (部分、派别) + -isan (名词后缀，支持者) → 党派的、偏颇的',
    'hypothesis': 'hypo- (在...下方) + thes/thesis (放置、设定) → 设在底部的假定 → 假说、前提',
    'synthesize': 'syn- (共同、聚合) + thes/thesis (放置) + -ize (使动) → 放在一起组合 → 合成、综合',
    'antithesis': 'anti- (相对、相反) + thesis (论题、观点) → 对立面、对立观点',
    'breakthrough': 'break (打破) + through (穿透) → 重大突破、突围',
    'benchmark': 'bench (工作台、基准) + mark (标记) → 基准、标准',
    'backbone': 'back (后背) + bone (骨头) → 脊梁骨、支柱',
    'backlash': 'back (向后) + lash (猛击) → 强烈反对、强烈反弹',
    'drawback': 'draw (拉、拖) + back (向后) → 往回拉的力量 → 缺点、障碍',
    'counterpart': 'counter- (对应) + part (部分、人) → 对应的人或物',
    'masterpiece': 'master (大师) + piece (作品) → 杰作、代表作',
    'mindset': 'mind (头脑、思维) + set (设定、固定) → 思维模式、心态',
    'outbreak': 'out (向外) + break (爆发、打破) → 疫情/战争爆发',
    'outcome': 'out (出来) + come (来到) → 产出、结果',
    'outlook': 'out (向外) + look (看) → 视野、前景、展望',
    'output': 'out (向外) + put (放置、输出) → 产量、输出',
    'outweigh': 'out- (超过) + weigh (称重、分量) → 重于、胜过',
    'overall': 'over (在...之上) + all (全部) → 总体上的、全面的',
    'overcome': 'over (跨过、在上) + come (来到) → 战胜、克服',
    'overlook': 'over (在上方、越过) + look (看) → 俯瞰 或 忽视、漏看',
    'overseas': 'over (跨越) + seas (海洋) → 海外的、国外的',
    'overview': 'over (全面、在上方) + view (观察) → 概览、全貌',
    'shortcoming': 'short (不足) + come (到来) + -ing → 不足之处、缺点',
    'standpoint': 'stand (站立) + point (点、位置) → 观察点、立场',
    'turnover': 'turn (翻转) + over (过来) → 营业额、人员流动率',
    'undergo': 'under (在...之下) + go (走过) → 经受、经历',
    'underlie': 'under (在...下方) + lie (躺、位于) → 构成...的基础',
    'underline': 'under (在...下方) + line (划线) → 在下方划线、强调',
    'undermine': 'under (在下方) + mine (挖坑道) → 从下方挖空地基 → 暗中破坏、削弱',
    'underpin': 'under (在下方) + pin (销钉、固定) → 从底部支撑、巩固',
    'upbeat': 'up (向上) + beat (节拍) → 节拍欢快的 → 乐观的、向上振奋的',
    'upgrade': 'up (向上) + grade (等级) → 提升等级、升级',
    'uphold': 'up (向上) + hold (举起、支撑) → 维护、支持、捍卫',
    'upright': 'up (直立) + right (端正) → 垂直的、正直的',
    'widespread': 'wide (广泛) + spread (传播、展开) → 普遍的、分布广泛的',
    'well-being': 'well (良好) + being (存在、生存) → 幸福、安康',
    'worthwhile': 'worth (值得) + while (时光、付出) → 值得花时间的',
    'workforce': 'work (工作) + force (力量、队伍) → 劳动力、全体员工',
    'workplace': 'work (工作) + place (场所) → 工作场所、职场',
    'layout': 'lay (放置) + out (向外、展开) → 布局、排版',
    'lifestyle': 'life (生活) + style (方式、风格) → 生活方式',
    'mainstream': 'main (主要) + stream (溪流、潮流) → 主流、主要趋势',
    'milestone': 'mile (英里) + stone (里程石) → 里程碑、重大转折点'
}

# 2. Prefixes
PREFIXES = [
    ('retro', 'retro- (向后、往回)'),
    ('counter', 'counter- (相反、反对、对应)'),
    ('contra', 'contra- (相反、对抗)'),
    ('contro', 'contro- (相反、对照)'),
    ('extra', 'extra- (超出、额外)'),
    ('extro', 'extro- (向外)'),
    ('hyper', 'hyper- (过度、极度、超越)'),
    ('hypo', 'hypo- (在...之下、次于)'),
    ('inter', 'inter- (在...之间、相互)'),
    ('intra', 'intra- (在...内部)'),
    ('intro', 'intro- (向内、入内)'),
    ('micro', 'micro- (微小)'),
    ('macro', 'macro- (宏观、巨大)'),
    ('multi', 'multi- (多、多样)'),
    ('omni', 'omni- (全、全能)'),
    ('trans', 'trans- (穿过、转变、转移)'),
    ('super', 'super- (超级、在上方、过度)'),
    ('supra', 'supra- (在...之上、超越)'),
    ('under', 'under- (在下方、不足、隐秘)'),
    ('anti', 'anti- (反对、抗击、预防)'),
    ('ante', 'ante- (在...之前、早于)'),
    ('auto', 'auto- (自身、自动)'),
    ('circum', 'circum- (围绕、周围、环绕)'),
    ('tele', 'tele- (远距离)'),
    ('pseudo', 'pseudo- (假、伪)'),
    ('quasi', 'quasi- (类似、准)'),
    ('semi', 'semi- (半、部分)'),
    ('mono', 'mono- (单一、单独)'),
    ('poly', 'poly- (多、多数)'),
    ('tri', 'tri- (三)'),
    ('sub', 'sub- (在...下方、次级)'),
    ('suc', 'suc- (在...下方、随后)'),
    ('suf', 'suf- (在...下方)'),
    ('sug', 'sug- (在...下方、暗中)'),
    ('sup', 'sup- (在...下方、支持)'),
    ('sur', 'sur- (在...之上、超过)'),
    ('sus', 'sus- (在...下方、自下而上支撑)'),
    ('sym', 'sym- (共同、相同)'),
    ('syn', 'syn- (共同、聚合)'),
    ('col', 'col- (共同、聚合)'),
    ('com', 'com- (共同、加强语气)'),
    ('con', 'con- (共同、加强语气)'),
    ('cor', 'cor- (共同、相互)'),
    ('co', 'co- (共同、联合)'),
    ('dis', 'dis- (分开、相反、否定)'),
    ('dif', 'dif- (分开、不同)'),
    ('dia', 'dia- (穿过、二者之间)'),
    ('pre', 'pre- (在...之前、预先)'),
    ('pro', 'pro- (向前、赞同、支持)'),
    ('per', 'per- (贯穿、完全、彻底)'),
    ('post', 'post- (在...之后)'),
    ('para', 'para- (在旁、类似、异常)'),
    ('peri', 'peri- (周围、外围)'),
    ('over', 'over- (过度、在上方、超越)'),
    ('fore', 'fore- (在前、预先)'),
    ('non', 'non- (非、不)'),
    ('mis', 'mis- (错误、不当)'),
    ('mal', 'mal- (恶、不良、错误)'),
    ('out', 'out- (超越、在外部、胜过)'),
    ('ab', 'ab- (离开、偏离)'),
    ('abs', 'abs- (离开、脱离)'),
    ('ad', 'ad- (朝向、加强)'),
    ('ac', 'ac- (朝向、加强)'),
    ('af', 'af- (朝向、加强)'),
    ('ag', 'ag- (朝向、加强)'),
    ('al', 'al- (朝向、加强)'),
    ('an', 'an- (无、不、非)'),
    ('ap', 'ap- (朝向、加强)'),
    ('ar', 'ar- (朝向、加强)'),
    ('as', 'as- (朝向、加强)'),
    ('at', 'at- (朝向、加强)'),
    ('de', 'de- (向下、去除、否定)'),
    ('ex', 'ex- (出、向外、前任)'),
    ('ef', 'ef- (出、向外)'),
    ('em', 'em- (使进入、置于...之中)'),
    ('en', 'en- (使进入、使成为)'),
    ('in', 'in- (不、非 或 向内、进入)'),
    ('im', 'im- (不、非 或 向内、进入)'),
    ('il', 'il- (不、非)'),
    ('ir', 'ir- (不、非)'),
    ('re', 're- (再、反复、向后、回)'),
    ('un', 'un- (不、非、取消)'),
    ('se', 'se- (分开、隔离)'),
    ('up', 'up- (向上、朝上)')
]

# 3. Classical Roots
ROOTS = [
    ('spect', 'spect/spic (看、观察)'),
    ('spic', 'spect/spic (看、观察)'),
    ('struct', 'struct (建造、构成)'),
    ('tract', 'tract (拉、吸引、抽出)'),
    ('dict', 'dict (说话、宣布)'),
    ('duct', 'duc/duct (引导、带来)'),
    ('duc', 'duc/duct (引导、带来)'),
    ('port', 'port (搬运、携带)'),
    ('scrib', 'scrib/script (写、记录)'),
    ('script', 'scrib/script (写、记录)'),
    ('press', 'press (挤压、压迫)'),
    ('vis', 'vis/vid (看见)'),
    ('vid', 'vis/vid (看见)'),
    ('voc', 'voc/vok (叫喊、声音)'),
    ('vok', 'voc/vok (叫喊、声音)'),
    ('vert', 'vert/vers (转动、转变)'),
    ('vers', 'vert/vers (转动、转变)'),
    ('pel', 'pel/puls (推、驱动)'),
    ('puls', 'pel/puls (推、驱动)'),
    ('ject', 'ject (扔、投射)'),
    ('pend', 'pend/pens (悬挂、衡量、支付)'),
    ('pens', 'pend/pens (悬挂、衡量、支付)'),
    ('mit', 'mit/miss (送出、派遣)'),
    ('miss', 'mit/miss (送出、派遣)'),
    ('cess', 'ced/ceed/cess (行走、退让)'),
    ('ceed', 'ced/ceed/cess (行走、退让)'),
    ('cede', 'ced/ceed/cess (行走、退让)'),
    ('cur', 'cur/curs (跑、流动、发生)'),
    ('curs', 'cur/curs (跑、流动、发生)'),
    ('fer', 'fer (带来、承受、运送)'),
    ('gener', 'gen/gener (出生、产生、种族)'),
    ('gen', 'gen/gener (出生、产生、种族)'),
    ('flu', 'flu/flux (流动)'),
    ('flux', 'flu/flux (流动)'),
    ('plic', 'plic/ply/plex (折叠、重叠)'),
    ('plex', 'plic/ply/plex (折叠、重叠)'),
    ('ply', 'plic/ply/plex (折叠、重叠)'),
    ('fact', 'fac/fact/fict (做、制造)'),
    ('fict', 'fac/fact/fict (做、制造)'),
    ('fect', 'fac/fact/fect (做、制造)'),
    ('fic', 'fac/fact/fic (做、制造)'),
    ('capt', 'cap/capt/cept (抓取、拿取、容纳)'),
    ('cept', 'cap/capt/cept (抓取、拿取、容纳)'),
    ('ceiv', 'ceiv/cept (抓取、接受)'),
    ('cip', 'cip/cept (抓取、拿取)'),
    ('tend', 'tend/tens/tent (伸展、倾向)'),
    ('tens', 'tend/tens/tent (伸展、倾向)'),
    ('tent', 'tend/tens/tent (伸展、倾向)'),
    ('serv', 'serv (保持、服务、观察)'),
    ('form', 'form (形状、形成)'),
    ('tain', 'tain/ten/tin (握住、保持、支撑)'),
    ('pos', 'pos/pon (放置、摆放)'),
    ('pon', 'pos/pon (放置、摆放)'),
    ('stat', 'stat/stit/sist (站立、设立、稳固)'),
    ('stit', 'stat/stit/sist (站立、设立、稳固)'),
    ('sist', 'stat/stit/sist (站立、设立、稳固)'),
    ('val', 'val/vail (强壮、价值)'),
    ('vail', 'val/vail (强壮、价值)'),
    ('clar', 'clar (清楚、明朗)'),
    ('path', 'path/pass (感受、受苦、疾病)'),
    ('scend', 'scend/scent (攀爬、上升)'),
    ('fid', 'fid/feder (信任、信念)'),
    ('cred', 'cred (相信、信任)'),
    ('chron', 'chron (时间)'),
    ('corp', 'corp (身体、组织)'),
    ('lect', 'leg/lig/lect (选择、收集、读)'),
    ('viv', 'viv/vit (生命、生活)'),
    ('vit', 'viv/vit (生命、活力)'),
    ('err', 'err (漫游、犯错)'),
    ('rog', 'rog (要求、询问)'),
    ('radic', 'radic (根、根本)'),
    ('turb', 'turb (混乱、骚动)'),
    ('tort', 'tort (扭曲、拧)'),
    ('vac', 'vac/van (空、虚无)'),
    ('luc', 'luc/lum/lux (光、明亮)'),
    ('lum', 'luc/lum/lux (光、明亮)'),
    ('solv', 'solv/solut (解开、溶解、偿还)'),
    ('solut', 'solv/solut (解开、解答)'),
    ('rupt', 'rupt (断裂、破裂)'),
    ('sect', 'sec/sect (切割、切开)'),
    ('quer', 'quer/quest/quir (寻求、询问)'),
    ('quest', 'quer/quest/quir (寻求、询问)'),
    ('quir', 'quer/quest/quir (寻求、询问)'),
    ('quis', 'quis/quest (寻求、获得)'),
    ('grad', 'grad/gress (步伐、行走、等级)'),
    ('gress', 'grad/gress (步伐、行走、等级)'),
    ('cide', 'cid/cide (切、杀、落下)'),
    ('cise', 'cis/cise (切、剪)'),
    ('fuse', 'fus/fuse (倾倒、融合)'),
    ('mort', 'mort (死亡)'),
    ('nov', 'nov/neo (新)'),
    ('prim', 'prim/prin (第一、原始)'),
    ('prin', 'prim/prin (第一、主要的)'),
    ('sens', 'sens/sent (感觉、意识)'),
    ('sent', 'sens/sent (感觉、意识)'),
    ('sumpt', 'sum/sumpt (拿取、总计、消耗)'),
    ('aud', 'aud/audit (听)'),
    ('audit', 'aud/audit (听、审理)'),
    ('bene', 'bene/bon (好、善)'),
    ('magn', 'magn/maj (大、宏大)'),
    ('doc', 'doc/doct (教导、学说)'),
    ('doct', 'doc/doct (教导、学说)'),
    ('hab', 'hab/hibit (拥有、居住、拿)'),
    ('hibit', 'hab/hibit (拥有、拿、持)'),
    ('memor', 'memor (记忆、记得)'),
    ('norm', 'norm (规范、标准)'),
    ('orig', 'orig (起源、开始)'),
    ('sci', 'sci (知道、科学)'),
    ('temp', 'temp/tempor (时间、节制)'),
    ('tempor', 'temp/tempor (时间、时代)'),
    ('term', 'term/termin (界限、末端、术语)'),
    ('termin', 'term/termin (界限、终结)'),
    ('urb', 'urb (城市)'),
    ('civ', 'civ/cit (公民、城市)'),
    ('popul', 'popul/publ (人民、大众)'),
    ('publ', 'popul/publ (公众、大众)'),
    ('soci', 'soci (结伴、社会)'),
    ('jur', 'jur/jud/just (法律、正义、判断)'),
    ('jud', 'jur/jud/just (法律、审判)'),
    ('just', 'jur/jud/just (公正、法律)'),
    ('medi', 'medi (中间、居中)'),
    ('centr', 'centr (中心)'),
    ('phon', 'phon (声音、语音)'),
    ('graph', 'graph/gram (写、画、图)'),
    ('gram', 'graph/gram (写、字、图)'),
    ('log', 'log/logy/loc (说话、学科、逻辑)'),
    ('loqu', 'loqu/loc (说话、交谈)'),
    ('nom', 'nom/onym (名字、法则)'),
    ('onym', 'nom/onym (名字)'),
    ('acu', 'acu/ac (尖、酸、敏锐)'),
    ('aer', 'aero/aer (空气、航空)'),
    ('aero', 'aero/aer (空气、航空)'),
    ('aesthet', 'aesthet (感觉、审美)'),
    ('agon', 'agon (挣扎、斗争)'),
    ('agr', 'agr/agri (农田、土地)'),
    ('alter', 'ali/alter (其他、改变)'),
    ('ali', 'ali/alter (其他、改变)'),
    ('alt', 'alt (高、高处)'),
    ('anim', 'anim (生命、心灵、精神)'),
    ('ann', 'ann/enn (年、年度)'),
    ('enn', 'ann/enn (年、年度)'),
    ('anthrop', 'anthrop (人类)'),
    ('apt', 'apt/ept (适应、适合、能力)'),
    ('ept', 'apt/ept (适应、能力)'),
    ('aqua', 'aqua (水)'),
    ('arch', 'arch (统治、首领、古老)'),
    ('arm', 'arm (武器、武装)'),
    ('art', 'art (技巧、艺术)'),
    ('astr', 'astr/aster (星星、天文)'),
    ('aster', 'astr/aster (星星、天文)'),
    ('aug', 'aug/auct/aux (增加、扩大)'),
    ('auct', 'aug/auct/aux (增加、扩大)'),
    ('bell', 'bell (战争、打斗)'),
    ('bio', 'bio (生命、生物)'),
    ('brev', 'brev (短、简短)'),
    ('cad', 'cad/cas/cid (落下、降临、发生)'),
    ('cas', 'cad/cas/cid (落下、降临、发生)'),
    ('cand', 'cand (白、发光、坦白)'),
    ('cant', 'cant/cent (唱、歌唱)'),
    ('carn', 'carn (肉体、肉)'),
    ('cav', 'cav (洞、空)'),
    ('celer', 'celer (快速、敏捷)'),
    ('cern', 'cern/cert (搞清、区别、确信)'),
    ('cert', 'cern/cert (确信、必定)'),
    ('cili', 'cili (召集、睫毛)'),
    ('circ', 'circ/cycl (圆、环绕)'),
    ('cycl', 'circ/cycl (圆、环绕)'),
    ('claim', 'claim/clam (呼喊、声称)'),
    ('clam', 'claim/clam (呼喊、声称)'),
    ('clin', 'clin (倾斜、弯曲)'),
    ('clos', 'clos/clud/clus (关闭、封锁)'),
    ('clud', 'clos/clud/clus (关闭、封锁)'),
    ('clus', 'clos/clud/clus (关闭、封锁)'),
    ('cogn', 'cogn/gnos (认识、知道)'),
    ('gnos', 'cogn/gnos (认识、知道)'),
    ('cord', 'cord/card (心、心脏、一致)'),
    ('card', 'cord/card (心、心脏)'),
    ('cosm', 'cosm (宇宙、秩序)'),
    ('cresc', 'cresc/cret (增长、生长)'),
    ('cret', 'cresc/cret (增长、分离)'),
    ('crit', 'crit/cris (判断、审判、批评)'),
    ('cris', 'crit/cris (危机、判断)'),
    ('cruc', 'cruc (十字、交叉、关键)'),
    ('culp', 'culp (罪过、责备)'),
    ('cura', 'cur/cura (关心、注意、治愈)'),
    ('dam', 'dam/demn (损害、惩罚)'),
    ('demn', 'dam/demn (损害、谴责)'),
    ('dem', 'dem (人民、民众)'),
    ('dent', 'dent/dont (牙齿)'),
    ('dign', 'dign (尊严、高贵)'),
    ('dol', 'dol (悲痛、忧伤)'),
    ('dom', 'dom (房屋、统治)'),
    ('don', 'don/dot (给予、赠送)'),
    ('dot', 'don/dot (给予)'),
    ('dorm', 'dorm (睡眠)'),
    ('dox', 'dox (观点、学说)'),
    ('dur', 'dur (持久、坚硬)'),
    ('dynam', 'dyn/dynam (力量、威力)'),
    ('eco', 'eco (家园、生态、经济)'),
    ('ego', 'ego (自我)'),
    ('empt', 'em/empt (拿取、获得、买)'),
    ('fam', 'fam/fa (说话、名声)'),
    ('fall', 'fall/fals (欺骗、错误)'),
    ('fals', 'fall/fals (欺骗、错误)'),
    ('feder', 'feder/fid (联盟、信任)'),
    ('ferv', 'ferv (热、沸腾)'),
    ('fil', 'fil (线、子女)'),
    ('fin', 'fin (界限、结束、最终)'),
    ('firm', 'firm (稳固、坚定)'),
    ('fix', 'fix (固定、确定)'),
    ('flam', 'flam (火焰、燃烧)'),
    ('flect', 'flect/flex (弯曲、折)'),
    ('flex', 'flect/flex (弯曲、折)'),
    ('flict', 'flict (打击、碰击)'),
    ('flor', 'flor/flour (花、繁荣)'),
    ('flour', 'flor/flour (花、繁荣)'),
    ('forc', 'forc/fort (强壮、力量)'),
    ('fort', 'forc/fort (强壮、力量)'),
    ('fract', 'frag/fract (打破、碎裂)'),
    ('frag', 'frag/fract (打破、碎裂)'),
    ('fring', 'frag/fract/fring (打破、侵犯)'),
    ('front', 'front (前额、前沿)'),
    ('fug', 'fug (逃跑、逃离)'),
    ('fund', 'fund/found (底部、基础、资金)'),
    ('found', 'fund/found (底部、基础)'),
    ('gam', 'gam (婚姻、结合)'),
    ('geo', 'geo (地球、土地)'),
    ('gest', 'ger/gest (带来、承载、产生)'),
    ('grat', 'grat (感激、取悦、恩惠)'),
    ('grav', 'grav (沉重、庄严)'),
    ('greg', 'greg (群体、聚集)'),
    ('haust', 'haur/haust (抽取、消耗、竭尽)'),
    ('heli', 'heli (太阳)'),
    ('herb', 'herb (植物、草)'),
    ('hes', 'her/hes (粘附、坚持)'),
    ('hetero', 'hetero (不同、异质)'),
    ('homo', 'homo/homeo (相同、同质)'),
    ('horr', 'horr (恐惧、发抖)'),
    ('hosp', 'hosp/host (客人、主人、招待)'),
    ('host', 'hosp/host (敌人、宿主、聚集)'),
    ('hum', 'hum (土地、泥土、卑微)'),
    ('hydr', 'hydr (水、液体)'),
    ('ide', 'ide/idea (思想、观念)'),
    ('idio', 'idio (个人的、独特的)'),
    ('ign', 'ign (火、点燃)'),
    ('insul', 'insul (岛屿、隔离)'),
    ('integr', 'integr (完整、整合)'),
    ('joc', 'joc (玩笑、幽默)'),
    ('join', 'join/junct (连接、结合)'),
    ('junct', 'join/junct (连接、结合)'),
    ('journ', 'journ (一天、日子、旅程)'),
    ('juven', 'juven (年轻、少年)'),
    ('labor', 'labor (劳动、工作)'),
    ('laps', 'laps (滑落、跌落)'),
    ('laud', 'laud (赞美、称赞)'),
    ('leas', 'lax/leas (松弛、释放)'),
    ('lev', 'lev (轻、升起、举起)'),
    ('liber', 'liber (自由、释放)'),
    ('libr', 'libr (天平、衡量)'),
    ('limin', 'limin (门槛、界限)'),
    ('lingu', 'lingu (语言、舌头)'),
    ('linqu', 'linqu/lict (留下、离开)'),
    ('lict', 'linqu/lict (留下、离开)'),
    ('liter', 'liter (文字、字母、学者)'),
    ('lith', 'lith (石头)'),
    ('lud', 'lud/lus (玩弄、扮演、欺骗)'),
    ('lus', 'lud/lus (玩弄、扮演、欺骗)'),
    ('manu', 'man/manu (手、操作)'),
    ('mand', 'mand (命令、委托)'),
    ('mania', 'mania (狂热、痴迷)'),
    ('mater', 'mater/matr (母亲、母体)'),
    ('matr', 'mater/matr (母亲、母体)'),
    ('mech', 'mech/mach (机器、机械)'),
    ('mach', 'mech/mach (机器、机械)'),
    ('med', 'med/medic (治疗、医治)'),
    ('medic', 'med/medic (治疗、医治)'),
    ('mend', 'mend (缺陷、修改)'),
    ('mens', 'mens/meas (测量、计算)'),
    ('meas', 'mens/meas (测量、计算)'),
    ('ment', 'ment (心智、思想、神智)'),
    ('merc', 'merc (交易、商品、报酬)'),
    ('merg', 'merg/mers (沉浸、没入)'),
    ('mers', 'merg/mers (沉浸、没入)'),
    ('meter', 'meter/metr (测量、计量)'),
    ('metr', 'meter/metr (测量、计量)'),
    ('migr', 'migr (迁移、移动)'),
    ('milit', 'milit (军队、士兵、战斗)'),
    ('mir', 'mir (惊奇、奇迹)'),
    ('misc', 'misc/mixt (混合、混杂)'),
    ('mixt', 'misc/mixt (混合、混杂)'),
    ('mobi', 'mob/mobi/mot/mov (移动、动摇)'),
    ('mot', 'mob/mobi/mot/mov (移动、动摇)'),
    ('mov', 'mob/mobi/mot/mov (移动、动摇)'),
    ('mod', 'mod (模式、风度、节制)'),
    ('monit', 'mon/monit (警告、提醒)'),
    ('monstr', 'monstr (显示、显露)'),
    ('morph', 'morph (形状、形态)'),
    ('muni', 'muni (公共职责、防御工事、赠礼)'),
    ('mut', 'mut (改变、变异)'),
    ('nat', 'nat/nasc (出生、天生)'),
    ('nasc', 'nat/nasc (出生、天生)'),
    ('naut', 'naut/nav (船、航行)'),
    ('nav', 'naut/nav (船、航行)'),
    ('necr', 'necr (死尸、坏死)'),
    ('nect', 'nect/nex (系结、连接)'),
    ('nex', 'nect/nex (系结、连接)'),
    ('neg', 'neg (否决、拒绝)'),
    ('neur', 'neur (神经)'),
    ('nihil', 'nihil (虚无、无)'),
    ('noc', 'noc/nox (伤害、有害)'),
    ('nox', 'noc/nox (伤害、黑夜)'),
    ('not', 'not (标记、知晓、注明)'),
    ('numer', 'numer (数量、数字)'),
    ('nunci', 'nunci/nounc (宣布、报告)'),
    ('nounc', 'nunci/nounc (宣布、报告)'),
    ('nutri', 'nutri (滋养、培育)'),
    ('ocul', 'ocul/opt (眼睛、视觉)'),
    ('opt', 'opt/ocul (选择、希望、视觉)'),
    ('odor', 'odor (气味、香气)'),
    ('oner', 'oner (负担、重任)'),
    ('oper', 'oper (工作、操作)'),
    ('ordin', 'ord/ordin (秩序、排列、命令)'),
    ('orn', 'orn (装饰、装备)'),
    ('ortho', 'ortho (正、直、正确)'),
    ('pac', 'pac (和平、安抚)'),
    ('palp', 'palp (摸、触、感知)'),
    ('pater', 'pater/patr (父亲、祖国)'),
    ('patr', 'pater/patr (父亲、祖国)'),
    ('pecun', 'pecun (金钱、财产)'),
    ('pept', 'pept/peps (消化)'),
    ('peps', 'pept/peps (消化)'),
    ('petit', 'pet/petit (追求、寻求、冲向)'),
    ('phil', 'phil (喜爱、亲近)'),
    ('phob', 'phob (害怕、恐惧)'),
    ('phor', 'phor/pher (带来、承载)'),
    ('phot', 'phot/photo (光、光明)'),
    ('pict', 'pict (绘画、描摹)'),
    ('plac', 'plac/pleas (取悦、平静、安抚)'),
    ('pleas', 'plac/pleas (取悦、平静)'),
    ('plan', 'plan (平坦、平面、计划)'),
    ('plaud', 'plaud/plaus/plod/plos (拍手、鼓掌、赞同)'),
    ('plaus', 'plaud/plaus/plod/plos (拍手、鼓掌、赞同)'),
    ('plod', 'plaud/plaus/plod/plos (拍手、鼓掌、爆炸)'),
    ('plos', 'plaud/plaus/plod/plos (鼓掌、爆炸)'),
    ('plet', 'ple/plet/plen (满、充满、填满)'),
    ('plen', 'ple/plet/plen (满、充满、完整)'),
    ('plor', 'plor (哀叹、呼喊)'),
    ('pneu', 'pneu (呼吸、气体)'),
    ('polis', 'pol/polis/polit (城市、政治)'),
    ('polit', 'pol/polis/polit (政治、城市、公民)'),
    ('pot', 'pot (能力、有力量 或 饮用)'),
    ('preci', 'preci/prais (价值、评价、赞美)'),
    ('prais', 'preci/prais (价值、赞赏)'),
    ('pred', 'pred (捕食、抢掠)'),
    ('prehend', 'prehend/prehens (抓住、理解、领会)'),
    ('prehens', 'prehend/prehens (抓住、理解、领会)'),
    ('priv', 'priv (私有、剥夺、单独)'),
    ('prob', 'prob/prov (检验、证明、正直)'),
    ('prov', 'prob/prov (检验、证明)'),
    ('propr', 'propr (自身、固有、恰当)'),
    ('psych', 'psych (心灵、精神、心理)'),
    ('pugn', 'pugn (打斗、拳头)'),
    ('punct', 'pung/punct (刺、点、尖锐)'),
    ('pung', 'pung/punct (刺、尖锐)'),
    ('pur', 'pur (纯洁、清白)'),
    ('put', 'put (思考、计算、修剪)'),
    ('pyr', 'pyr (火)'),
    ('qual', 'qual (性质、特征、品质)'),
    ('quant', 'quant (数量、多少)'),
    ('quie', 'quie (安静、平静、平息)'),
    ('radi', 'radi/ray (光线、辐射、光芒)'),
    ('rapt', 'rap/rapt (抓取、掠夺、狂喜)'),
    ('rect', 'rect/reg (直、正、引导、统治)'),
    ('rid', 'rid/ris (笑、嘲笑)'),
    ('ris', 'rid/ris (笑、嘲笑)'),
    ('rod', 'rod/ros (咬、侵蚀、啮)'),
    ('ros', 'rod/ros (咬、侵蚀)'),
    ('rot', 'rot/roll (轮子、旋转)'),
    ('roll', 'rot/roll (滚动、卷)'),
    ('rud', 'rud (原始、粗糙)'),
    ('sacr', 'sacr/secr/sanct (神圣、宗教)'),
    ('secr', 'sacr/secr/sanct (神圣、隐秘)'),
    ('sanct', 'sacr/secr/sanct (神圣、尊贵)'),
    ('sag', 'sag (聪明、敏锐、智慧)'),
    ('sult', 'sal/sult/sail/sil (跳跃、结果、冒犯)'),
    ('sail', 'sal/sult/sail/sil (跳跃、袭击)'),
    ('salv', 'salv/salu (安全、拯救、健康)'),
    ('salu', 'salv/salu (健康、安全)'),
    ('san', 'san (健康、神智清醒)'),
    ('sanguin', 'sanguin (血液、血气)'),
    ('satis', 'sat/satis (足够、满意)'),
    ('scop', 'scop (观察、窥镜)'),
    ('scrut', 'scrut (细查、探究)'),
    ('secut', 'secut/sequ (跟随、继续)'),
    ('sequ', 'secut/sequ (跟随、顺序)'),
    ('sess', 'sed/sid/sess (坐、会议)'),
    ('simil', 'sem/simil/simul (相似、如同)'),
    ('simul', 'sem/simil/simul (相同、模拟)'),
    ('sen', 'sen (年老、长者)'),
    ('sever', 'sever (严厉、严重)'),
    ('sign', 'sign (标记、记号、签名)'),
    ('sinu', 'sinu (弯曲、波状)'),
    ('somn', 'somn (睡眠、做梦)'),
    ('soph', 'soph (智慧、学问)'),
    ('sorb', 'sorb/sorpt (吸入、吸收)'),
    ('sorpt', 'sorb/sorpt (吸入、吸收)'),
    ('sper', 'sper (希望 或 散开)'),
    ('spher', 'spher (球体、范围)'),
    ('spir', 'spir (呼吸、精神、灵魂)'),
    ('splend', 'splend (光辉、壮丽)'),
    ('spond', 'spond/spons (承诺、答应、响应)'),
    ('spons', 'spond/spons (承诺、响应、赞助)'),
    ('stell', 'stell (星星、星座)'),
    ('stigm', 'stigm/stinct (刺、印记、斑点)'),
    ('stinct', 'stingu/stinct (刺、熄灭、区别)'),
    ('stingu', 'stingu/stinct (刺、熄灭、区别)'),
    ('strict', 'string/strict/strain (拉紧、束缚、限制)'),
    ('string', 'string/strict/strain (拉紧、束缚)'),
    ('strain', 'string/strict/strain (拉紧、尽力)'),
    ('stru', 'stru/struct (建造、构成)'),
    ('stud', 'stud (热心、致力于、求学)'),
    ('suav', 'suav (甜美、温和)'),
    ('surg', 'surg/surrect (升起、涌起)'),
    ('surrect', 'surg/surrect (升起、复活)'),
    ('tact', 'tact/tag/tang/ting (接触、触摸)'),
    ('tang', 'tact/tag/tang/ting (触摸、触及)'),
    ('tail', 'tail (切割、修剪)'),
    ('tard', 'tard (迟缓、延迟)'),
    ('tax', 'tax (排列、税收、分类)'),
    ('techn', 'techn (技能、艺术、工艺)'),
    ('teg', 'teg/tect (覆盖、掩护)'),
    ('tect', 'teg/tect (覆盖、保护、发现)'),
    ('terr', 'terr (土地、地球 或 恐惧、惊吓)'),
    ('test', 'test (见证、证据、考试)'),
    ('text', 'tex/text (编织、文本、正文)'),
    ('theo', 'theo/the (神、神明)'),
    ('therm', 'therm (热、温度)'),
    ('thesis', 'thesis/thet (放置、论题)'),
    ('thet', 'thesis/thet (放置、设定)'),
    ('tim', 'tim (害怕、胆怯)'),
    ('toler', 'toler (忍受、容忍)'),
    ('tribut', 'tribu/tribut (给予、分配、贡奉)'),
    ('tribu', 'tribu/tribut (给予、分配、贡奉)'),
    ('trit', 'trit (摩擦、磨损)'),
    ('trud', 'trud/trus (推、伸出、强加)'),
    ('trus', 'trud/trus (推、突出)'),
    ('tum', 'tum (肿胀、隆起)'),
    ('umbr', 'umbr (阴影、遮蔽)'),
    ('und', 'und (波动、波浪)'),
    ('ung', 'ung/unct (涂抹、涂油)'),
    ('unct', 'ung/unct (涂抹、涂油)'),
    ('uni', 'uni (单一、一致)'),
    ('urg', 'urg/erg (工作、催促、驱动)'),
    ('erg', 'urg/erg (工作、能量)'),
    ('vad', 'vad/vas (走、行走)'),
    ('vas', 'vad/vas (走、器皿)'),
    ('vag', 'vag (漫游、游荡)'),
    ('var', 'var (变化、多样、斑驳)'),
    ('veh', 'veh/vect (搬运、载运)'),
    ('vect', 'veh/vect (载运、引导)'),
    ('vell', 'vell/vuls (拔、撕扯)'),
    ('vuls', 'vell/vuls (撕扯、抽搐)'),
    ('ven', 'ven/vent (来到、走来)'),
    ('vent', 'ven/vent (来到、走来、出口)'),
    ('vend', 'vend (出售、售卖)'),
    ('vener', 'vener (尊敬、崇敬)'),
    ('ver', 'ver (真实、确实)'),
    ('verb', 'verb (词语、言语)'),
    ('verd', 'verd (绿色、生机)'),
    ('verg', 'verg (倾斜、趋向)'),
    ('vest', 'vest (衣服、穿衣、赋予)'),
    ('vestig', 'vestig (脚印、痕迹)'),
    ('veter', 'vet/veter (老、资深)'),
    ('via', 'vi/via/vey/voy (道路、途径)'),
    ('vey', 'vi/via/vey/voy (道路、运送)'),
    ('voy', 'vi/via/vey/voy (道路、航程)'),
    ('vibr', 'vibr (振动、摇摆)'),
    ('vict', 'vict/vinc (征服、胜过)'),
    ('vinc', 'vict/vinc (征服、胜过)'),
    ('vig', 'vig/veil (警觉、充满活力)'),
    ('vindic', 'vindic (申明、辩护、复仇)'),
    ('virtu', 'virtu (美德、功效、力量)'),
    ('viti', 'viti (过错、损坏)'),
    ('volv', 'volv/volut (旋转、卷动)'),
    ('volut', 'volv/volut (旋转、卷动)'),
    ('vor', 'vor (吞食、贪吃)'),
    ('vow', 'vow/vot (发誓、立誓、投票)'),
    ('vot', 'vow/vot (发誓、奉献、投票)'),
    ('vulg', 'vulg (平民、大众、粗俗)'),
    ('vulner', 'vulner (创伤、伤害)')
]

# 4. Suffixes
SUFFIXES = [
    ('ization', '-ization (名词后缀，...化)'),
    ('isation', '-isation (名词后缀，...化)'),
    ('ability', '-ability (名词后缀，可...性)'),
    ('ibility', '-ibility (名词后缀，可...性)'),
    ('lessness', '-lessness (名词后缀，无...状态)'),
    ('fulness', '-fulness (名词后缀，充满...的状态)'),
    ('ologist', '-ologist (名词后缀，...学专家)'),
    ('ology', '-ology (名词后缀，...学科)'),
    ('cracy', '-cracy (名词后缀，...统治体制)'),
    ('phobia', '-phobia (名词后缀，...恐惧症)'),
    ('mania', '-mania (名词后缀，...狂热)'),
    ('ation', '-ation (名词后缀，行为/结果)'),
    ('ition', '-ition (名词后缀，行为/过程)'),
    ('ution', '-ution (名词后缀，行为/结果)'),
    ('sion', '-sion (名词后缀，行为/状态)'),
    ('tion', '-tion (名词后缀，行为/状态)'),
    ('ment', '-ment (名词后缀，行为/结果/状态)'),
    ('ness', '-ness (名词后缀，...的性质/状态)'),
    ('ship', '-ship (名词后缀，身份/关系/技能)'),
    ('hood', '-hood (名词后缀，时期/状态/身份)'),
    ('ance', '-ance (名词后缀，性质/状态)'),
    ('ence', '-ence (名词后缀，性质/状态)'),
    ('ancy', '-ancy (名词后缀，性质/状态)'),
    ('ency', '-ency (名词后缀，性质/状态)'),
    ('ism', '-ism (名词后缀，...主义/学说/特征)'),
    ('ist', '-ist (名词后缀，...家/专业人员)'),
    ('ity', '-ity (名词后缀，...的性质/状态)'),
    ('ety', '-ety (名词后缀，...的性质/状态)'),
    ('ery', '-ery (名词后缀，场所/行为/行业)'),
    ('ary', '-ary (形容词/名词后缀，...的人/物/相关的)'),
    ('ory', '-ory (形容词/名词后缀，有...性质的/场所)'),
    ('ant', '-ant (形容词/名词后缀，...的/人/剂)'),
    ('ent', '-ent (形容词/名词后缀，...的/人/剂)'),
    ('able', '-able (形容词后缀，可...的、能...的)'),
    ('ible', '-ible (形容词后缀，易...的、可...的)'),
    ('ious', '-ious (形容词后缀，充满...的)'),
    ('eous', '-eous (形容词后缀，有...性质的)'),
    ('uous', '-uous (形容词后缀，具有...特性的)'),
    ('ous', '-ous (形容词后缀，具有...性质的)'),
    ('ive', '-ive (形容词后缀，具有...倾向的)'),
    ('ial', '-ial (形容词后缀，关于...的)'),
    ('ual', '-ual (形容词后缀，关于...的)'),
    ('al', '-al (形容词后缀，具有...特性的)'),
    ('ic', '-ic (形容词后缀，...特性的)'),
    ('ical', '-ical (形容词后缀，具有...学术特性的)'),
    ('ish', '-ish (形容词/动词后缀，有...特征的/使...)'),
    ('ful', '-ful (形容词后缀，充满...的)'),
    ('less', '-less (形容词后缀，无...的、不...的)'),
    ('some', '-some (形容词后缀，引起...的、易于...的)'),
    ('ward', '-ward (副词/形容词后缀，朝...方向)'),
    ('like', '-like (形容词后缀，像...一样的)'),
    ('wise', '-wise (副词后缀，在...方面、像...一样)'),
    ('ize', '-ize (使动动词后缀，使...化)'),
    ('ise', '-ise (使动动词后缀，使...化)'),
    ('ify', '-ify (使动动词后缀，使变得...)'),
    ('ate', '-ate (动词/形容词后缀，使.../具有...特性的)'),
    ('en', '-en (使动动词/形容词后缀，使变得.../由...制成的)'),
    ('ly', '-ly (副词/形容词后缀，以...方式/有...特性的)')
]

def generate_root_breakdown(word, translation=""):
    w = word.lower().strip()
    if not w:
        return ""
        
    if w in SPECIAL_ROOTS:
        return SPECIAL_ROOTS[w]
        
    p_hit = None
    r_hit = None
    s_hit = None
    
    # 1. Match Prefix
    rem = w
    for p_key, p_desc in PREFIXES:
        if rem.startswith(p_key) and len(rem) >= len(p_key) + 3:
            p_hit = p_desc
            rem = rem[len(p_key):]
            break
            
    # 2. Match Suffix
    for s_key, s_desc in SUFFIXES:
        if rem.endswith(s_key) and len(rem) >= len(s_key) + 2:
            s_hit = s_desc
            rem = rem[:-len(s_key)]
            break
            
    # 3. Match Root
    for r_key, r_desc in ROOTS:
        if r_key in rem or (len(r_key) >= 4 and r_key in w):
            r_hit = r_desc
            break
            
    parts = []
    if p_hit:
        parts.append(p_hit)
    if r_hit:
        parts.append(r_hit)
    elif rem and len(rem) >= 3 and (p_hit or s_hit):
        parts.append(f"词干 [{rem}]")
    if s_hit:
        parts.append(s_hit)
        
    if len(parts) >= 2:
        return ' + '.join(parts) + ' → 词义引申'
    elif r_hit:
        return f"{r_hit} 衍生核心词"
    elif p_hit:
        return f"{p_hit} + 核心词干构词"
    elif s_hit:
        return f"核心词干 [{rem or w}] + {s_hit}"
    else:
        return f"考研核心本词 [{w}]（学术高频认知词干）"

def run_update_all_roots():
    with open(WORDS_PATH, 'r', encoding='utf-8') as f:
        doc = json.load(f)
    words = doc['words']
    active_words = [w for w in words if w.get('active') is not False]
    
    for w in active_words:
        w['root'] = generate_root_breakdown(w['word'], w.get('translation', ''))
        
    doc['DATA_VERSION'] = "5894-v9-root-100"
    doc['data_version'] = "5894-v9-root-100"
    
    with open(WORDS_PATH, 'w', encoding='utf-8') as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        
    print(f"Updated all {len(active_words)} active words with refined root breakdowns.")

if __name__ == '__main__':
    run_update_all_roots()
