# -*- coding: utf-8 -*-
"""
Academic Synonyms, Antonyms, and Exam Question Type (exam_tag) Engine for Kaoyan Lexicon.
Provides comprehensive synonym paraphrasing networks and Kaoyan paper type contextualization.
"""

import json, os, sys, re

sys.stdout.reconfigure(encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, 'data')
WORDS_PATH = os.path.join(DATA_DIR, 'words.json')

# 1. Kaoyan Question Type Tag Rules
EXAM_TAGS = {
    # Reading Attitude Words (阅读态度词)
    'attitude': [
        'critical', 'skeptical', 'doubtful', 'suspicious', 'cautious', 'conservative',
        'optimistic', 'positive', 'enthusiastic', 'supportive', 'appreciative', 'approving',
        'pessimistic', 'negative', 'disapproving', 'scornful', 'cynical', 'sarcastic',
        'objective', 'neutral', 'impartial', 'dispassionate', 'unbiased', 'detached',
        'indifferent', 'apathetic', 'unconcerned', 'aloof', 'casual',
        'ambivalent', 'mixed', 'compromising', 'tentative', 'reserved', 'pragmatic'
    ],
    # Cloze Logical Connectors (完形逻辑衔接词)
    'cloze_logic': [
        'furthermore', 'moreover', 'besides', 'additionally', 'meanwhile',
        'consequently', 'therefore', 'hence', 'thus', 'accordingly', 'thereby',
        'nevertheless', 'nonetheless', 'however', 'conversely', 'whereas', 'notwithstanding',
        'instead', 'otherwise', 'alternatively', 'specifically', 'namely',
        'incidentally', 'likewise', 'similarly', 'incidentally', 'ultimately', 'eventually'
    ],
    # Translation Abstract Concepts (翻译抽象高频词)
    'translation': [
        'substantiate', 'manifest', 'manifestation', 'underlie', 'paradox', 'paradoxical',
        'infrastructure', 'imperative', 'intrinsic', 'extrinsic', 'phenomenon', 'hypothesis',
        'philosophical', 'ideology', 'mechanism', 'equilibrium', 'heterogeneous', 'homogeneous',
        'inherent', 'superficial', 'subtle', 'profound', 'cognitive', 'synthesize', 'dilemma',
        'rationality', 'precedent', 'conception', 'perspective', 'evolutionary', 'dynamic'
    ],
    # Essay Writing Golden Substitutes (写作黄金替换词)
    'writing': [
        'vital', 'crucial', 'pivotal', 'paramount', 'indispensable', 'essential',
        'exert', 'trigger', 'foster', 'cultivate', 'facilitate', 'propel', 'boost',
        'diminish', 'curb', 'hinder', 'hamper', 'undermine', 'jeopardize',
        'flourish', 'thrive', 'prosper', 'soar', 'skyrocket', 'plunge', 'plummet',
        'depict', 'illustrate', 'portray', 'demonstrate', 'reveal', 'exemplify',
        'overwhelming', 'striking', 'remarkable', 'pronounced', 'noteworthy', 'abundant'
    ]
}

# 2. Curated Synonym & Antonym Network Dictionary for Academic English
SYN_ANT_PAIRS = {
    'abandon': ('discard, relinquish, forsake, desert', 'retain, maintain, cherish'),
    'abbreviate': ('shorten, condense, abridge, curtail', 'expand, lengthen, prolong'),
    'abnormal': ('anomalous, irregular, eccentric, aberrant', 'normal, typical, conventional'),
    'abundant': ('plentiful, copious, ample, profuse', 'scarce, meager, deficient'),
    'accelerate': ('quicken, expedite, speed up, hasten', 'decelerate, delay, retard'),
    'accumulate': ('amass, aggregate, collect, gather', 'disperse, scatter, dissipate'),
    'accurate': ('precise, exact, correct, meticulous', 'inaccurate, erroneous, flawed'),
    'acquire': ('obtain, gain, attain, procure', 'lose, forfeit, surrender'),
    'acute': ('sharp, keen, piercing, intense', 'blunt, dull, mild'),
    'adapt': ('adjust, accommodate, conform, modify', 'resist, persist, retain'),
    'adequate': ('sufficient, enough, ample, competent', 'inadequate, insufficient, meager'),
    'adhere': ('stick, cling, attach, comply', 'separate, detach, deviate'),
    'admire': ('appreciate, respect, esteem, praise', 'despise, scorn, disdain'),
    'adopt': ('embrace, accept, assume, approve', 'reject, abandon, discard'),
    'advocate': ('champion, support, endorse, promote', 'oppose, refute, discourage'),
    'affluent': ('wealthy, prosperous, opulent, rich', 'poor, impoverished, destitute'),
    'aggravate': ('worsen, exacerbate, intensify, irritate', 'alleviate, mitigate, relieve'),
    'alien': ('foreign, exotic, unfamiliar, strange', 'native, local, indigenous'),
    'alleviate': ('relieve, ease, soothe, mitigate', 'aggravate, intensify, worsen'),
    'alter': ('modify, change, transform, adjust', 'preserve, maintain, retain'),
    'ambiguous': ('vague, obscure, equivocal, unclear', 'clear, lucid, explicit'),
    'ambitious': ('aspiring, enterprising, bold, driven', 'lazy, passive, unmotivated'),
    'amplify': ('expand, magnify, enlarge, intensify', 'diminish, reduce, contract'),
    'apparent': ('evident, obvious, manifest, visible', 'hidden, obscure, concealed'),
    'appeal': ('attract, plead, petition, charm', 'repel, disgust, reject'),
    'applaud': ('praise, acclaim, commend, cheer', 'criticize, condemn, boo'),
    'approach': ('method, access, path, approximate', 'depart, retreat, distance'),
    'appropriate': ('suitable, fitting, proper, apt', 'inappropriate, improper, unfit'),
    'approve': ('endorse, sanction, authorize, accept', 'disapprove, reject, veto'),
    'arbitrary': ('random, capricious, subjective, erratic', 'rational, objective, reasoned'),
    'arise': ('emerge, originate, stem, appear', 'disappear, vanish, subside'),
    'arouse': ('stimulate, awaken, provoke, incite', 'calm, soothe, suppress'),
    'artificial': ('synthetic, man-made, fabricated, faux', 'natural, genuine, authentic'),
    'aspire': ('seek, aim, desire, crave', 'disregard, abandon, renounce'),
    'assert': ('affirm, declare, maintain, claim', 'deny, disclaim, refute'),
    'assess': ('evaluate, appraise, estimate, judge', 'ignore, overlook, neglect'),
    'attain': ('achieve, accomplish, reach, gain', 'fail, lose, surrender'),
    'authentic': ('genuine, real, legitimate, valid', 'fake, counterfeit, forged'),
    'authority': ('power, command, expert, jurisdiction', 'subordination, impotence, amateur'),
    'autonomous': ('independent, sovereign, self-governing', 'dependent, subject, controlled'),
    'barrier': ('obstacle, hurdle, impediment, block', 'aid, opening, catalyst'),
    'benefit': ('advantage, profit, gain, privilege', 'harm, loss, detriment'),
    'bias': ('prejudice, partiality, preconception', 'fairness, neutrality, objectivity'),
    'boost': ('elevate, enhance, amplify, raise', 'hinder, depress, suppress'),
    'brief': ('concise, succinct, short, momentary', 'lengthy, verbose, prolonged'),
    'brilliant': ('radiant, splendid, ingenious, stellar', 'dull, dim, mediocre'),
    'candidate': ('applicant, nominee, contender, contestant', 'incumbent, non-applicant'),
    'capable': ('competent, able, qualified, skilled', 'incapable, incompetent, inept'),
    'capture': ('seize, apprehend, arrest, snare', 'release, liberate, free'),
    'cautious': ('wary, prudent, heedful, vigilant', 'reckless, rash, careless'),
    'cease': ('stop, terminate, halt, discontinue', 'continue, commence, proceed'),
    'champion': ('advocate, defender, winner, victor', 'opponent, critic, loser'),
    'chaos': ('disorder, turmoil, confusion, havoc', 'order, harmony, peace'),
    'cherish': ('treasure, value, appreciate, prize', 'neglect, discard, despise'),
    'chronic': ('persistent, continuous, lingering, habitual', 'acute, temporary, transient'),
    'clarify': ('explain, elucidate, illuminate, resolve', 'confuse, obscure, muddle'),
    'climax': ('pinnacle, zenith, culmination, peak', 'anticlimax, nadir, base'),
    'coexist': ('cohabit, synchronize, harmonize', 'conflict, clash, compete'),
    'cognitive': ('mental, intellectual, cerebral, rational', 'emotional, intuitive, physical'),
    'collaborate': ('cooperate, team up, coordinate, conspire', 'compete, oppose, resist'),
    'collapse': ('breakdown, tumble, crumble, failure', 'rise, thrive, prosper'),
    'commence': ('begin, initiate, launch, embark', 'conclude, terminate, finish'),
    'commit': ('pledge, devote, dedicate, perpetrate', 'withdraw, withhold, default'),
    'compact': ('dense, concise, solid, condensed', 'loose, diffuse, sprawling'),
    'compatible': ('harmonious, consistent, congenial, fitting', 'incompatible, conflicting, discordant'),
    'compel': ('force, coerce, constrain, obligate', 'dissuade, permit, allow'),
    'compensate': ('reimburse, indemnify, offset, balance', 'deprive, fine, penalize'),
    'competent': ('capable, qualified, proficient, adept', 'incompetent, inept, unqualified'),
    'complain': ('grumble, protest, lament, whine', 'praise, commend, applaud'),
    'complement': ('supplement, enhance, round out, balance', 'diminish, conflict, detract'),
    'complex': ('complicated, intricate, elaborate, sophisticated', 'simple, plain, basic'),
    'comply': ('conform, obey, submit, observe', 'defy, disobey, resist'),
    'component': ('element, constituent, ingredient, part', 'whole, aggregate, entirety'),
    'comprehend': ('understand, grasp, perceive, fathom', 'misunderstand, miss, mistake'),
    'comprehensive': ('thorough, all-inclusive, extensive, exhaustive', 'limited, narrow, partial'),
    'compromise': ('negotiate, concede, settle, jeopardize', 'stand firm, dispute, refuse'),
    'conceal': ('hide, disguise, mask, camouflage', 'reveal, disclose, expose'),
    'concede': ('admit, acknowledge, surrender, yield', 'deny, dispute, contest'),
    'conceive': ('devise, formulate, imagine, grasp', 'destroy, ignore, misunderstand'),
    'concentrate': ('focus, center, converge, condense', 'distract, dissipate, scatter'),
    'conclude': ('deduce, finalize, infer, complete', 'commence, begin, initiate'),
    'concrete': ('tangible, solid, specific, definite', 'abstract, vague, indefinite'),
    'condemn': ('denounce, criticize, sentence, censure', 'praise, commend, acquit'),
    'conduct': ('manage, guide, execute, behave', 'mismanage, abandon, neglect'),
    'confer': ('bestow, grant, consult, deliberate', 'withhold, revoke, deprive'),
    'confide': ('trust, reveal, disclose, entrust', 'withhold, conceal, distrust'),
    'confident': ('assured, positive, poised, certain', 'doubtful, hesitant, timid'),
    'confirm': ('verify, corroborate, ratify, validate', 'refute, deny, invalidate'),
    'conflict': ('clash, dispute, discord, battle', 'harmony, peace, agreement'),
    'conform': ('adapt, comply, obey, fit', 'rebel, deviate, diverge'),
    'confront': ('encounter, face, oppose, challenge', 'evade, avoid, dodge'),
    'confuse': ('puzzle, baffle, bewilder, confound', 'clarify, enlighten, illuminate'),
    'consequent': ('resulting, ensuing, subsequent, following', 'prior, antecedent, preceding'),
    'conserve': ('preserve, protect, maintain, save', 'waste, squander, deplete'),
    'considerable': ('substantial, significant, immense, large', 'trivial, negligible, minor'),
    'consistent': ('coherent, constant, compatible, steady', 'inconsistent, erratic, conflicting'),
    'consolidate': ('strengthen, reinforce, unify, merge', 'weaken, dissolve, fragment'),
    'conspicuous': ('prominent, noticeable, striking, salient', 'hidden, inconspicuous, subtle'),
    'constant': ('continual, perpetual, unceasing, steady', 'intermittent, sporadic, volatile'),
    'constitute': ('form, comprise, establish, compose', 'dissolve, break, dismantle'),
    'constrain': ('restrict, limit, compel, restrain', 'free, release, liberate'),
    'construct': ('build, erect, fabricate, formulate', 'demolish, destroy, dismantle'),
    'consult': ('confer, advise, counsel, refer', 'ignore, disregard, neglect'),
    'consume': ('deplete, expend, absorb, devour', 'produce, generate, conserve'),
    'contemporary': ('modern, current, present-day, peer', 'ancient, archaic, obsolete'),
    'contempt': ('scorn, disdain, derision, disrespect', 'admiration, respect, esteem'),
    'contend': ('assert, compete, strive, dispute', 'yield, surrender, concede'),
    'context': ('environment, background, setting, framework', 'isolation, vacuum'),
    'contradict': ('rebut, refute, negate, oppose', 'confirm, corroborate, agree'),
    'contrary': ('opposite, adverse, conflicting, hostile', 'similar, aligned, harmonious'),
    'contrast': ('difference, distinction, disparity, oppose', 'similarity, resemblance, likeness'),
    'contribute': ('donate, provide, assist, add', 'withhold, withdraw, subtract'),
    'controversy': ('dispute, debate, quarrel, contention', 'consensus, agreement, harmony'),
    'convene': ('assemble, gather, meet, summon', 'disperse, adjourn, disband'),
    'conventional': ('traditional, orthodox, customary, standard', 'unconventional, novel, radical'),
    'converge': ('merge, meet, unite, join', 'diverge, separate, disperse'),
    'convert': ('transform, change, adapt, switch', 'retain, preserve, maintain'),
    'convey': ('transmit, communicate, transport, express', 'withhold, suppress, retain'),
    'convince': ('persuade, assure, sway, satisfy', 'dissuade, discourage, doubt'),
    'cooperate': ('collaborate, assist, conspire, unite', 'oppose, resist, compete'),
    'cope': ('manage, tackle, endure, survive', 'collapse, surrender, fail'),
    'cordial': ('warm, gracious, genial, friendly', 'cold, hostile, aloof'),
    'correlate': ('associate, connect, align, relate', 'disconnect, separate, dissociate'),
    'corrupt': ('dishonest, depraved, tainted, crooked', 'honest, ethical, pure'),
    'counterfeit': ('fake, forged, fraudulent, spurious', 'genuine, authentic, real'),
    'counterpart': ('equivalent, match, parallel, peer', 'opposite, antithesis'),
    'creative': ('innovative, inventive, original, imaginative', 'unimaginative, conventional, derivative'),
    'credible': ('believable, plausible, dependable, reliable', 'incredible, implausible, dubious'),
    'critical': ('crucial, vital, analytical, judgmental', 'trivial, negligible, approving'),
    'crucial': ('pivotal, essential, vital, decisive', 'minor, secondary, inconsequential'),
    'cultivate': ('foster, nurture, develop, grow', 'neglect, destroy, abandon'),
    'cumbersome': ('unwieldy, clumsy, burdensome, awkward', 'manageable, convenient, graceful'),
    'curb': ('restrain, control, suppress, restrict', 'unleash, encourage, foster'),
    'curious': ('inquisitive, eager, strange, unusual', 'indifferent, ordinary, typical'),
    'cynical': ('pessimistic, distrustful, skeptical, scornful', 'optimistic, trusting, idealistic'),
    'decay': ('decompose, rot, deteriorate, decline', 'thrive, flourish, grow'),
    'deceive': ('mislead, delude, cheat, dupe', 'enlighten, guide, be honest'),
    'decline': ('decrease, diminish, refuse, deteriorate', 'increase, accept, thrive'),
    'decrease': ('diminish, reduce, shrink, lessen', 'increase, augment, expand'),
    'dedicate': ('devote, consecrate, pledge, assign', 'abandon, misuse, neglect'),
    'deduce': ('infer, conclude, derive, reason', 'guess, assume, speculate'),
    'defend': ('protect, guard, shield, uphold', 'attack, assault, surrender'),
    'deficient': ('lacking, inadequate, scarce, flawed', 'sufficient, abundant, adequate'),
    'deficit': ('shortage, deficiency, loss, shortfall', 'surplus, profit, excess'),
    'definite': ('clear, explicit, certain, specific', 'vague, indefinite, ambiguous'),
    'degrade': ('demote, humble, demean, deteriorate', 'elevate, upgrade, honor'),
    'deliberate': ('intentional, calculated, ponder, reflect', 'accidental, hasty, impulsive'),
    'delicate': ('fragile, subtle, dainty, exquisite', 'robust, coarse, harsh'),
    'demonstrate': ('show, reveal, manifest, prove', 'conceal, hide, disprove'),
    'denounce': ('condemn, criticize, attack, accuse', 'praise, laud, commend'),
    'dense': ('thick, compact, crowded, heavy', 'sparse, thin, loose'),
    'deny': ('refuse, reject, repudiate, disown', 'admit, acknowledge, concede'),
    'depict': ('portray, illustrate, describe, represent', 'misrepresent, distort, hide'),
    'deplete': ('exhaust, drain, consume, reduce', 'replenish, restore, fill'),
    'depress': ('sadden, discourage, devalue, sink', 'uplift, encourage, boost'),
    'deprive': ('strip, dispossess, rob, deny', 'provide, bestow, endow'),
    'derive': ('obtain, trace, originate, infer', 'give, bestow, misdirect'),
    'despise': ('scorn, disdain, loathe, detest', 'admire, respect, cherish'),
    'destroy': ('ruin, demolish, annihilate, shatter', 'construct, build, create'),
    'detach': ('separate, disconnect, disengage, isolate', 'attach, connect, unite'),
    'deteriorate': ('worsen, decline, degenerate, decay', 'improve, enhance, flourish'),
    'determine': ('decide, resolve, ascertain, dictate', 'hesitate, vacillate, waver'),
    'devastate': ('destroy, ravage, ruin, wreck', 'restore, construct, preserve'),
    'deviate': ('diverge, stray, digress, wander', 'conform, follow, align'),
    'devote': ('dedicate, allocate, commit, surrender', 'withhold, neglect, abandon'),
    'diminish': ('decrease, lessen, shrink, dwindle', 'increase, enlarge, expand'),
    'disaster': ('catastrophe, calamity, tragedy, ruin', 'blessing, prosperity, triumph'),
    'discard': ('abandon, dump, throw away, reject', 'keep, retain, preserve'),
    'discharge': ('release, dismiss, emit, unload', 'employ, absorb, detain'),
    'discipline': ('training, control, field, regulation', 'disorder, chaos, indulgence'),
    'disclose': ('reveal, divulge, expose, uncover', 'conceal, hide, disguise'),
    'discount': ('deduct, reduce, disregard, dismiss', 'increase, amplify, emphasize'),
    'discourage': ('dissuade, deter, disheart, prevent', 'encourage, inspire, motivate'),
    'discreet': ('prudent, cautious, tactful, guarded', 'indiscreet, rash, careless'),
    'discrepancy': ('difference, divergence, disparity, variance', 'consistency, similarity, alignment'),
    'discriminate': ('distinguish, differentiate, segregate', 'unify, treat equally, blend'),
    'disdain': ('scorn, contempt, derision, spurn', 'admiration, esteem, respect'),
    'disguise': ('camouflage, mask, conceal, cloak', 'reveal, uncover, expose'),
    'dismiss': ('discharge, reject, discard, dispel', 'hire, accept, welcome'),
    'disperse': ('scatter, dissipate, diffuse, distribute', 'assemble, gather, collect'),
    'displace': ('replace, relocate, dislodge, supplant', 'reinstate, keep, settle'),
    'display': ('show, exhibit, reveal, manifest', 'hide, conceal, mask'),
    'dispose': ('arrange, discard, incline, settle', 'keep, retain, confuse'),
    'dispute': ('quarrel, debate, conflict, challenge', 'agree, settle, harmonize'),
    'disrupt': ('interrupt, disturb, shatter, derail', 'stabilize, organize, maintain'),
    'disseminate': ('distribute, broadcast, spread, propagate', 'suppress, conceal, gather'),
    'dissolve': ('melt, disband, terminate, vanish', 'coagulate, form, establish'),
    'distinct': ('different, clear, separate, definite', 'indistinct, identical, vague'),
    'distinguish': ('differentiate, discern, characterize', 'confuse, mistake, blur'),
    'distort': ('deform, twist, warp, falsify', 'clarify, represent, preserve'),
    'distract': ('divert, deflect, confuse, bewilder', 'focus, concentrate, guide'),
    'distribute': ('allocate, disperse, deliver, share', 'collect, hoard, gather'),
    'distrust': ('suspect, doubt, question, mistrust', 'trust, rely, believe'),
    'disturb': ('trouble, bother, disrupt, agitate', 'calm, soothe, settle'),
    'diverge': ('deviate, branch, separate, differ', 'converge, merge, unite'),
    'diverse': ('varied, manifold, heterogeneous, sundry', 'uniform, identical, homogenous'),
    'divert': ('deflect, redirect, distract, amuse', 'focus, direct, continue'),
    'divine': ('godly, sacred, heavenly, intuit', 'mortal, earthly, secular'),
    'doctrine': ('dogma, precept, tenet, creed', 'heresy, doubt, skepticism'),
    'dominate': ('command, govern, control, overshadow', 'submit, yield, obey'),
    'dormant': ('latent, inactive, sluggish, resting', 'active, alert, dynamic'),
    'drastic': ('radical, severe, extreme, rigorous', 'mild, moderate, gentle'),
    'dubious': ('doubtful, questionable, suspicious, uncertain', 'certain, reliable, trustworthy'),
    'durable': ('lasting, enduring, resilient, sturdy', 'fragile, perishable, fleeting'),
    'dwell': ('reside, inhabit, linger, ponder', 'leave, depart, wander'),
    'dynamic': ('energetic, vibrant, active, forceful', 'static, sluggish, passive'),
    'eccentric': ('odd, peculiar, erratic, unconventional', 'conventional, normal, typical'),
    'echo': ('resonate, reverberate, repeat, reflect', 'silence, muffle, suppress'),
    'eclipse': ('overshadow, surpass, darken, diminish', 'illuminate, enhance, highlight'),
    'elaborate': ('detailed, intricate, develop, expand', 'simple, brief, plain'),
    'elevate': ('raise, hoist, promote, exalt', 'demote, lower, depress'),
    'eliminate': ('eradicate, remove, abolish, exterminate', 'create, retain, include'),
    'eloquent': ('articulate, expressive, fluent, persuasive', 'inarticulate, clumsy, hesitant'),
    'elucidate': ('clarify, explain, illustrate, illuminate', 'obscure, confuse, complicate'),
    'elusive': ('slippery, intangible, subtle, evasive', 'obvious, tangible, direct'),
    'embark': ('commence, board, launch, undertake', 'disembark, conclude, end'),
    'embrace': ('hug, adopt, welcome, encompass', 'reject, shun, repudiate'),
    'emerge': ('appear, arise, surface, emanate', 'disappear, submerge, vanish'),
    'eminent': ('distinguished, prominent, renowned, famous', 'obscure, unknown, ordinary'),
    'emit': ('release, discharge, radiate, exhale', 'absorb, ingest, retain'),
    'emphasize': ('stress, highlight, underscore, accentuate', 'downplay, ignore, overlook'),
    'empirical': ('practical, experimental, observed, factual', 'theoretical, speculative, abstract'),
    'enable': ('empower, facilitate, allow, permit', 'prevent, disable, inhibit'),
    'encounter': ('meet, face, confront, undergo', 'avoid, evade, bypass'),
    'encourage': ('inspire, boost, support, foster', 'discourage, deter, hinder'),
    'endeavor': ('strive, attempt, venture, effort', 'quit, abandon, neglect'),
    'endorse': ('approve, support, sanction, back', 'oppose, reject, condemn'),
    'endure': ('tolerate, bear, withstand, persist', 'succumb, collapse, perish'),
    'energetic': ('vigorous, dynamic, lively, brisk', 'lethargic, tired, passive'),
    'enforce': ('impose, execute, compel, administer', 'abandon, waive, disregard'),
    'engage': ('participate, absorb, captivate, hire', 'disengage, release, ignore'),
    'enhance': ('improve, augment, elevate, heighten', 'diminish, impair, degrade'),
    'enlighten': ('illuminate, educate, inform, edify', 'confuse, mislead, deceive'),
    'enormous': ('huge, immense, massive, gigantic', 'tiny, minute, microscopic'),
    'enrich': ('enhance, augment, improve, fertilize', 'deplete, impoverish, drain'),
    'ensure': ('guarantee, secure, assure, certify', 'jeopardize, risk, imperil'),
    'entail': ('involve, necessitate, require, impose', 'exclude, eliminate, omit'),
    'entertain': ('amuse, delight, harbor, consider', 'bore, reject, dismiss'),
    'enthusiastic': ('eager, passionate, ardent, zealous', 'indifferent, apathetic, reluctant'),
    'entitle': ('qualify, authorize, enable, name', 'disqualify, forbid, deny'),
    'entity': ('unit, body, being, existence', 'nonentity, nothingness, void'),
    'entrepreneur': ('businessman, founder, innovator, tycoon', 'employee, follower'),
    'envision': ('imagine, visualize, foresee, anticipate', 'ignore, disregard, miss'),
    'episode': ('incident, chapter, installment, event', 'totality, entirety, whole'),
    'equator': ('middle line, centerline', 'pole'),
    'equilibrium': ('balance, stability, poise, parity', 'imbalance, instability, chaos'),
    'equip': ('furnish, provide, arm, outfit', 'strip, disarm, deprive'),
    'equivalent': ('equal, identical, comparable, parallel', 'different, disparate, unequal'),
    'eradicate': ('eliminate, destroy, wipe out, exterminate', 'foster, nurture, plant'),
    'erroneous': ('incorrect, mistaken, flawed, inaccurate', 'accurate, correct, valid'),
    'escalate': ('intensify, heighten, increase, surge', 'de-escalate, lessen, subside'),
    'escape': ('flee, avoid, evade, elude', 'capture, confront, face'),
    'essential': ('vital, crucial, fundamental, basic', 'optional, trivial, peripheral'),
    'establish': ('found, institute, build, prove', 'destroy, abolish, refute'),
    'esteem': ('respect, admire, revere, value', 'disdain, scorn, despise'),
    'estimate': ('evaluate, assess, appraise, calculate', 'measure exactly, prove'),
    'eternal': ('perpetual, everlasting, endless, timeless', 'transient, temporary, fleeting'),
    'ethical': ('moral, principled, righteous, honorable', 'unethical, immoral, corrupt'),
    'evaluate': ('assess, judge, appraise, estimate', 'overlook, ignore, misjudge'),
    'eventual': ('ultimate, final, resulting, concluding', 'initial, primary, starting'),
    'evident': ('obvious, clear, apparent, manifest', 'obscure, hidden, doubtful'),
    'evoke': ('provoke, summon, awaken, elicit', 'suppress, stifle, calm'),
    'evolve': ('develop, progress, unfold, transform', 'stagnate, regress, decay'),
    'exaggerate': ('overstate, magnify, inflate, amplify', 'understate, downplay, minimize'),
    'exceed': ('surpass, transcend, outdo, top', 'fall short, fail, lag'),
    'excel': ('surpass, outshine, dominate, master', 'fail, lag, fall behind'),
    'exceptional': ('extraordinary, remarkable, rare, stellar', 'ordinary, mediocre, average'),
    'excessive': ('extreme, redundant, exorbitant, surplus', 'meager, moderate, scarce'),
    'exclude': ('omit, ban, bar, ostracize', 'include, welcome, admit'),
    'exclusive': ('sole, unique, private, restricted', 'inclusive, common, public'),
    'exemplify': ('illustrate, typify, demonstrate, embody', 'contradict, misrepresent'),
    'exempt': ('excuse, release, spared, immune', 'liable, subject, obligated'),
    'exhaust': ('deplete, drain, fatigue, tire', 'replenish, refresh, energize'),
    'exhibit': ('display, reveal, show, demonstrate', 'hide, conceal, cloak'),
    'expand': ('enlarge, inflate, broaden, extend', 'contract, shrink, compress'),
    'expedite': ('accelerate, hasten, speed up, facilitate', 'delay, impede, hinder'),
    'expel': ('eject, banish, oust, dismiss', 'admit, welcome, shelter'),
    'explicit': ('direct, clear, plain, unambiguous', 'implicit, vague, ambiguous'),
    'exploit': ('utilize, leverage, abuse, capitalize', 'neglect, waste, respect'),
    'explore': ('investigate, probe, examine, survey', 'ignore, overlook, avoid'),
    'expose': ('uncover, reveal, disclose, subject', 'conceal, hide, protect'),
    'exquisite': ('refined, delicate, superb, flawless', 'crude, clumsy, coarse'),
    'extend': ('prolong, lengthen, expand, stretch', 'shorten, curtail, contract'),
    'extinct': ('vanished, dead, defunct, obsolete', 'alive, living, thriving'),
    'extinguish': ('quench, stifle, snuff, put out', 'ignite, kindle, spark'),
    'extraordinary': ('remarkable, exceptional, stunning, rare', 'ordinary, common, mediocre'),
    'extravagant': ('wasteful, lavish, exorbitant, reckless', 'frugal, thrifty, moderate'),
    'extreme': ('radical, drastic, intense, utmost', 'moderate, mild, average'),
    'fabricate': ('construct, invent, forge, devise', 'demolish, discover, reveal'),
    'facilitate': ('ease, assist, promote, expedite', 'impede, hinder, obstruct'),
    'faction': ('bloc, camp, clique, sector', 'whole, totality, unity'),
    'fade': ('dim, wither, vanish, decline', 'brighten, flourish, grow'),
    'faithful': ('loyal, reliable, devoted, accurate', 'faithless, disloyal, false'),
    'fallacy': ('misconception, delusion, error, flaw', 'truth, fact, axiom'),
    'falsify': ('forge, distort, alter, fake', 'verify, validate, authenticate'),
    'famine': ('starvation, scarcity, drought, dearth', 'abundance, feast, plenty'),
    'fascinate': ('captivate, charm, enchant, enthrall', 'bore, repel, disgust'),
    'fatal': ('deadly, lethal, mortal, ruinous', 'harmless, beneficial, healing'),
    'feasible': ('viable, practicable, workable, achievable', 'infeasible, impossible, absurd'),
    'feature': ('trait, aspect, attribute, highlight', 'whole, context'),
    'feeble': ('weak, frail, fragile, faint', 'strong, robust, sturdy'),
    'fierce': ('ferocious, savage, violent, intense', 'gentle, mild, tame'),
    'figure': ('number, shape, person, compute', 'ignore, overlook'),
    'finite': ('limited, bounded, restricted, definite', 'infinite, boundless, endless'),
    'flaw': ('defect, blemish, fault, glitch', 'perfection, strength, merit'),
    'flee': ('escape, retreat, vanish, run away', 'remain, confront, stay'),
    'fleet': ('swift, rapid, armada, flotilla', 'sluggish, slow, stationary'),
    'flexible': ('pliable, adaptable, versatile, supple', 'rigid, inflexible, stubborn'),
    'flourish': ('thrive, prosper, bloom, succeed', 'wither, decline, decay'),
    'fluctuate': ('vary, alternate, wave, oscillate', 'stabilize, remain, balance'),
    'fluid': ('liquid, flowing, adaptable, shifting', 'solid, rigid, fixed'),
    'focus': ('concentrate, center, pinpoint, spotlight', 'distract, scatter, diffuse'),
    'forbid': ('prohibit, ban, bar, disallow', 'allow, permit, authorize'),
    'force': ('compel, coerce, power, energy', 'persuade, request, weakness'),
    'forecast': ('predict, foresee, project, anticipate', 'recollect, record, verify'),
    'foresee': ('anticipate, envision, predict, expect', 'ignore, overlook, miss'),
    'forge': ('create, construct, falsify, shape', 'destroy, demolish, dismantle'),
    'format': ('structure, layout, arrangement, form', 'chaos, randomness, disorder'),
    'formidable': ('daunting, intimidating, dread, tough', 'easy, trivial, weak'),
    'foster': ('nurture, cultivate, encourage, rear', 'discourage, neglect, abandon'),
    'fragile': ('delicate, brittle, frail, vulnerable', 'sturdy, resilient, durable'),
    'fragment': ('piece, portion, scrap, fraction', 'whole, entirety, aggregate'),
    'framework': ('structure, skeleton, architecture, scheme', 'chaos, formlessness'),
    'frank': ('honest, candid, straightforward, direct', 'deceitful, evasive, secretive'),
    'fraud': ('deceit, scam, fake, counterfeit', 'honesty, integrity, fairness'),
    'frequent': ('regular, recurrent, common, repeated', 'rare, occasional, seldom'),
    'frown': ('glower, scowl, disapprove, grimace', 'smile, grin, beam'),
    'fruitful': ('productive, fertile, rewarding, prolific', 'fruitless, barren, futile'),
    'frustrate': ('thwart, defeat, disappoint, baffle', 'fulfill, encourage, facilitate'),
    'fundamental': ('basic, primary, essential, root', 'secondary, superficial, minor'),
    'furious': ('enraged, fierce, irate, turbulent', 'calm, placid, serene'),
    'furnish': ('provide, supply, equip, decorate', 'strip, deprive, empty'),
    'furthermore': ('moreover, besides, in addition, additionally', 'otherwise, instead'),
    'futile': ('useless, vain, pointless, ineffective', 'fruitful, effective, useful'),
    'gain': ('obtain, acquire, profit, benefit', 'lose, forfeit, suffer'),
    'gather': ('assemble, collect, accumulate, glean', 'scatter, disperse, distribute'),
    'general': ('broad, universal, widespread, collective', 'specific, particular, individual'),
    'generate': ('produce, create, induce, spawn', 'destroy, terminate, extinguish'),
    'generous': ('magnanimous, lavish, bountiful, kind', 'stingy, selfish, meager'),
    'genuine': ('authentic, real, honest, pure', 'fake, forged, artificial'),
    'gigantic': ('immense, colossal, huge, massive', 'tiny, dwarf, microscopic'),
    'glance': ('peek, glimpse, scan, flash', 'stare, gaze, scrutinize'),
    'glare': ('glow, scowl, flare, shine', 'smile, beam, twinkle'),
    'gleam': ('shine, glimmer, flash, beam', 'darken, fade, obscure'),
    'glimpse': ('sight, peek, brief look, view', 'examination, study, gaze'),
    'gloomy': ('dismal, bleak, depressed, somber', 'cheerful, bright, radiant'),
    'glory': ('honor, renown, triumph, praise', 'disgrace, shame, ignominy'),
    'gorgeous': ('magnificent, splendid, radiant, stunning', 'ugly, plain, repulsive'),
    'graceful': ('elegant, poised, subtle, agile', 'clumsy, awkward, crude'),
    'gradual': ('progressive, steady, piecemeal, slow', 'sudden, abrupt, rapid'),
    'grasp': ('seize, clutch, understand, fathom', 'release, drop, misunderstand'),
    'gratitude': ('thankfulness, appreciation, acknowledgment', 'ingratitude, ungratefulness'),
    'gravity': ('seriousness, solemnity, weight, pull', 'levity, triviality, lightness'),
    'grief': ('sorrow, mourning, heartache, sadness', 'joy, delight, ecstasy'),
    'grim': ('stern, bleak, forbidding, harsh', 'cheerful, pleasant, bright'),
    'gross': ('flagrant, total, coarse, bulky', 'refined, net, delicate'),
    'guarantee': ('ensure, secure, warrant, pledge', 'risk, gamble, endanger'),
    'halt': ('stop, pause, suspend, freeze', 'proceed, continue, resume'),
    'hamper': ('hinder, impede, obstruct, restrict', 'facilitate, aid, foster'),
    'handicap': ('disability, impediment, disadvantage, drawback', 'advantage, asset, benefit'),
    'handy': ('convenient, useful, accessible, skilled', 'unwieldy, useless, clumsy'),
    'harbor': ('shelter, protect, cherish, dock', 'eject, expose, expel'),
    'harden': ('solidify, toughen, fortify, temper', 'soften, weaken, melt'),
    'harm': ('damage, injure, impair, hurt', 'benefit, heal, protect'),
    'harmony': ('concord, agreement, unity, peace', 'discord, conflict, chaos'),
    'harsh': ('severe, rigorous, cruel, abrasive', 'gentle, mild, pleasant'),
    'hasten': ('accelerate, rush, expedite, hurry', 'delay, slow, postpone'),
    'hasty': ('rash, hurried, impulsive, rushed', 'deliberate, careful, slow'),
    'haunt': ('plague, obsess, torment, visit', 'leave, soothe, comfort'),
    'hazard': ('danger, peril, risk, jeopardy', 'safety, security, protection'),
    'hectic': ('frantic, chaotic, busy, turbulent', 'calm, peaceful, serene'),
    'heed': ('notice, observe, pay attention, regard', 'ignore, neglect, disregard'),
    'heighten': ('elevate, amplify, sharpen, enhance', 'lower, diminish, reduce'),
    'heir': ('successor, beneficiary, inheritor', 'predecessor, donor'),
    'hesitate': ('waver, falter, pause, vacillate', 'resolve, decide, proceed'),
    'hideous': ('repulsive, monstrous, dreadful, ugly', 'beautiful, lovely, pleasant'),
    'highlight': ('accentuate, stress, feature, illuminate', 'obscure, downplay, hide'),
    'hinder': ('hamper, obstruct, impede, delay', 'help, promote, facilitate'),
    'hint': ('clue, suggestion, inkling, imply', 'declaration, certainty, fact'),
    'hollow': ('empty, void, sunken, false', 'solid, full, genuine'),
    'homely': ('plain, cozy, simple, unpretentious', 'glamorous, fancy, elegant'),
    'homogeneous': ('uniform, identical, consistent, alike', 'heterogeneous, varied, diverse'),
    'hostile': ('antagonistic, adverse, aggressive, enemy', 'friendly, cordial, peaceful'),
    'huge': ('immense, gigantic, vast, colossal', 'tiny, miniature, small'),
    'humble': ('modest, meek, respectful, lowly', 'arrogant, proud, boastful'),
    'humiliate': ('shame, degrade, dishonor, mortify', 'honor, praise, elevate'),
    'hybrid': ('crossbreed, composite, mixture, blend', 'purebred, unmixed, pure'),
    'hypothesis': ('theory, proposition, assumption, premise', 'fact, proof, reality'),
    'identical': ('duplicate, indistinguishable, twin, matching', 'distinct, diverse, different'),
    'identify': ('recognize, determine, distinguish, classify', 'confuse, mistake, overlook'),
    'idle': ('inactive, lazy, redundant, stagnant', 'active, industrious, diligent'),
    'ignite': ('kindle, spark, trigger, inflame', 'extinguish, quench, douse'),
    'ignore': ('disregard, overlook, neglect, dismiss', 'notice, regard, attend'),
    'illuminate': ('enlighten, brighten, clarify, explain', 'darken, obscure, confuse'),
    'illusion': ('delusion, fantasy, mirage, deception', 'reality, truth, fact'),
    'illustrate': ('depict, demonstrate, clarify, explain', 'obscure, confuse, hide'),
    'imitate': ('emulate, mimic, copy, mirror', 'originate, create, invent'),
    'immense': ('huge, vast, enormous, gigantic', 'tiny, minute, small'),
    'imminent': ('impending, looming, near, approaching', 'distant, remote, delayed'),
    'immune': ('exempt, protected, resistant, safe', 'susceptible, vulnerable, liable'),
    'impact': ('influence, impression, collision, effect', 'insignificance, neutrality'),
    'impartial': ('unbiased, objective, neutral, fair', 'biased, partial, prejudiced'),
    'impede': ('hinder, obstruct, hamper, delay', 'accelerate, facilitate, assist'),
    'imperative': ('urgent, essential, mandatory, crucial', 'optional, trivial, unnecessary'),
    'imperial': ('royal, majestic, sovereign, regal', 'plebeian, common, humble'),
    'impetus': ('momentum, stimulus, impulse, drive', 'hindrance, obstacle, inertia'),
    'implement': ('execute, enforce, realize, tool', 'abandon, neglect, repeal'),
    'implicit': ('implied, tacit, latent, indirect', 'explicit, direct, stated'),
    'imply': ('suggest, hint, signify, denote', 'state directly, declare, express'),
    'impose': ('inflict, levy, force, dictate', 'waive, remove, lift'),
    'impressive': ('striking, formidable, magnificent, grand', 'unimpressive, mediocre, plain'),
    'improve': ('enhance, ameliorate, boost, upgrade', 'worsen, deteriorate, impair'),
    'impulse': ('urge, instinct, momentum, incentive', 'deliberation, hesitation, reason'),
    'inadequate': ('deficient, lacking, scarce, insufficient', 'adequate, sufficient, ample'),
    'inappropriate': ('unfit, improper, unsuitable, untimely', 'appropriate, proper, fitting'),
    'incline': ('tilt, lean, tend, predispose', 'straighten, level, flatten'),
    'include': ('contain, comprise, embrace, incorporate', 'exclude, omit, eliminate'),
    'incorporate': ('integrate, merge, combine, include', 'separate, divide, detach'),
    'incredible': ('unbelievable, fabulous, marvelous, astounding', 'credible, plausible, ordinary'),
    'incur': ('induce, invite, suffer, sustain', 'avoid, evade, shun'),
    'indifferent': ('apathetic, unconcerned, neutral, detached', 'enthusiastic, eager, concerned'),
    'indigenous': ('native, aboriginal, endemic, local', 'foreign, alien, imported'),
    'indispensable': ('essential, vital, crucial, necessary', 'dispensable, redundant, useless'),
    'induce': ('prompt, cause, stimulate, provoke', 'prevent, inhibit, dissuade'),
    'inevitable': ('unavoidable, inescapable, destined, sure', 'avoidable, preventable, uncertain'),
    'infant': ('baby, newborn, toddler, nascent', 'adult, mature, veteran'),
    'infect': ('contaminate, taint, corrupt, pollute', 'purify, clean, disinfect'),
    'infer': ('deduce, conclude, gather, surmise', 'state, declare, assert'),
    'inferior': ('subordinate, lower, lesser, poorer', 'superior, greater, better'),
    'infinite': ('boundless, endless, limitless, vast', 'finite, limited, bounded'),
    'inflation': ('expansion, rise, swell, increase', 'deflation, shrink, contraction'),
    'inflict': ('impose, administer, deliver, wreak', 'withhold, spare, protect'),
    'influence': ('impact, sway, affect, dominate', 'neutrality, impotence'),
    'inform': ('notify, educate, advise, reveal', 'conceal, deceive, hide'),
    'infrastructure': ('framework, base, foundation, footing', 'superstructure, apex'),
    'ingenious': ('clever, inventive, brilliant, shrewd', 'clumsy, foolish, uncreative'),
    'inherent': ('intrinsic, innate, essential, built-in', 'extrinsic, acquired, alien'),
    'inherit': ('derive, acquire, succeed, receive', 'forfeit, give, surrender'),
    'inhibit': ('suppress, restrain, hinder, obstruct', 'encourage, stimulate, foster'),
    'initial': ('primary, first, early, starting', 'final, ultimate, terminal'),
    'initiate': ('commence, launch, institute, trigger', 'terminate, finish, halt'),
    'injure': ('harm, wound, damage, impair', 'heal, cure, protect'),
    'innate': ('inborn, native, inherent, natural', 'acquired, learned, alien'),
    'innocent': ('guiltless, pure, naive, harmless', 'guilty, corrupt, sinful'),
    'innovate': ('invent, pioneer, introduce, modernize', 'stagnate, copy, duplicate'),
    'inquire': ('ask, investigate, probe, query', 'answer, declare, respond'),
    'insane': ('mad, crazy, lunatic, irrational', 'sane, rational, sound'),
    'insight': ('perception, understanding, discernment, vision', 'blindness, ignorance, oversight'),
    'insist': ('persist, demand, assert, maintain', 'waver, yield, surrender'),
    'inspect': ('examine, scrutinize, check, audit', 'overlook, ignore, skip'),
    'inspire': ('motivate, stimulate, encourage, animate', 'discourage, depress, deter'),
    'install': ('set up, establish, place, inaugurate', 'uninstall, remove, dismantle'),
    'instance': ('example, case, illustration, sample', 'rule, theory, principle'),
    'instant': ('immediate, prompt, direct, urgent', 'delayed, slow, gradual'),
    'instinct': ('intuition, impulse, knack, flair', 'reason, logic, deliberation'),
    'institute': ('establish, found, set up, organization', 'abolish, dissolve, cancel'),
    'instruct': ('teach, guide, command, direct', 'learn, follow, obey'),
    'instrument': ('tool, device, apparatus, medium', 'obstacle, hindrance'),
    'insult': ('offend, affront, abuse, slight', 'praise, flatter, honor'),
    'integrate': ('unify, combine, assimilate, synthesize', 'segregate, isolate, separate'),
    'integrity': ('honesty, virtue, wholeness, soundness', 'corruption, deceit, deceitfulness'),
    'intellect': ('mind, brain, reason, intelligence', 'emotion, ignorance, instinct'),
    'intense': ('fierce, extreme, acute, severe', 'mild, weak, moderate'),
    'intend': ('mean, aim, plan, propose', 'neglect, ignore, overlook'),
    'interact': ('communicate, connect, interface, engage', 'isolate, detach, ignore'),
    'interfere': ('intrude, intervene, meddle, disrupt', 'assist, support, facilitate'),
    'interior': ('internal, inside, inner, domestic', 'exterior, outer, external'),
    'intermediate': ('middle, transitional, halfway, median', 'extreme, primary, advanced'),
    'interpret': ('explain, translate, decipher, construe', 'misinterpret, distort, confuse'),
    'interrupt': ('disrupt, suspend, interfere, break', 'continue, resume, maintain'),
    'intervene': ('interfere, arbitrate, mediate, intrude', 'withdraw, ignore, stand by'),
    'intimate': ('close, confidential, personal, privy', 'distant, formal, public'),
    'intricate': ('complex, complicated, elaborate, tangled', 'simple, plain, direct'),
    'intrigue': ('fascinate, charm, plot, scheme', 'bore, repel, disgust'),
    'intrinsic': ('inherent, essential, internal, innate', 'extrinsic, external, accidental'),
    'introduce': ('present, launch, insert, preface', 'conclude, withdraw, remove'),
    'invade': ('assault, conquer, overrun, breach', 'defend, protect, retreat'),
    'invalid': ('null, void, baseless, unsound', 'valid, legitimate, sound'),
    'invariable': ('constant, steady, unchanging, unalterable', 'variable, erratic, volatile'),
    'invent': ('devise, create, innovate, fabricate', 'copy, reproduce, imitate'),
    'invest': ('allocate, fund, endow, dedicate', 'divest, withdraw, squander'),
    'investigate': ('probe, examine, inspect, explore', 'ignore, overlook, disregard'),
    'invisible': ('unseen, hidden, imperceptible, covert', 'visible, apparent, clear'),
    'invoke': ('summon, call on, cite, appeal', 'dismiss, banish, ignore'),
    'involve': ('engage, entail, implicate, include', 'exclude, isolate, omit'),
    'ironic': ('sarcastic, cynical, paradoxical, satirical', 'literal, sincere, direct'),
    'irrational': ('illogical, absurd, foolish, senseless', 'rational, logical, reasonable'),
    'isolate': ('separate, insulate, detach, quarantine', 'integrate, unite, connect'),
    'issue': ('problem, matter, release, publish', 'withhold, suppress, hide'),
    'jeopardize': ('endanger, risk, threaten, compromise', 'protect, secure, safeguard'),
    'joy': ('delight, bliss, glee, happiness', 'grief, sorrow, sadness'),
    'judgment': ('verdict, decision, opinion, discernment', 'indecision, hesitation, confusion'),
    'junction': ('crossroads, intersection, connection, joint', 'separation, gap, division'),
    'justify': ('defend, vindicate, validate, excuse', 'condemn, accuse, invalidate'),
    'keen': ('sharp, eager, intense, acute', 'dull, blunt, indifferent'),
    'landmark': ('milestone, monument, benchmark, hallmark', 'triviality, detail'),
    'latent': ('dormant, hidden, potential, quiescent', 'manifest, active, apparent'),
    'launch': ('initiate, discharge, start, propel', 'halt, cancel, terminate'),
    'lavish': ('extravagant, opulent, generous, profuse', 'meager, frugal, stingy'),
    'legacy': ('inheritance, bequest, heritage, tradition', 'forfeiture, loss'),
    'legitimate': ('lawful, valid, genuine, legal', 'illegitimate, illegal, fake'),
    'leisure': ('relaxation, spare time, recreation, ease', 'labor, work, hustle'),
    'lenient': ('merciful, tolerant, mild, clement', 'strict, severe, harsh'),
    'lethal': ('deadly, fatal, mortal, destructive', 'harmless, healing, safe'),
    'leverage': ('influence, capitalize, harness, exploit', 'waste, forfeit, misuse'),
    'liberate': ('release, free, emancipate, unchain', 'enslave, imprison, detain'),
    'linger': ('loiter, remain, persist, delay', 'hasten, leave, depart'),
    'literary': ('scholarly, poetic, academic, literate', 'illiterate, crude, vulgar'),
    'lofty': ('elevated, noble, grand, towering', 'humble, low, base'),
    'lucid': ('clear, coherent, luminous, distinct', 'obscure, muddy, confusing'),
    'ludicrous': ('absurd, ridiculous, preposterous, laughable', 'sensible, serious, logical'),
    'lure': ('entice, tempt, seduce, bait', 'repel, warn, deter'),
    'magnificent': ('splendid, grand, noble, glorious', 'plain, modest, poor'),
    'maintain': ('preserve, sustain, assert, uphold', 'abandon, neglect, discontinue'),
    'manifest': ('evident, obvious, reveal, display', 'hidden, obscure, conceal'),
    'manipulate': ('handle, control, influence, engineer', 'mismanage, submit, follow'),
    'marginal': ('minor, peripheral, negligible, borderline', 'central, essential, core'),
    'massive': ('huge, bulky, colossal, substantial', 'tiny, slender, fragile'),
    'mastery': ('command, dominance, skill, expertise', 'ignorance, incompetence, novice'),
    'mature': ('adult, ripe, developed, seasoned', 'immature, green, juvenile'),
    'mediate': ('arbitrate, reconcile, negotiate, resolve', 'provoke, agitate, divide'),
    'mediocre': ('average, ordinary, commonplace, passable', 'exceptional, brilliant, superior'),
    'menace': ('threat, danger, peril, jeopardize', 'comfort, protect, shelter'),
    'merge': ('combine, fuse, unite, blend', 'separate, divide, split'),
    'meticulous': ('precise, scrupulous, careful, thorough', 'careless, sloppy, hasty'),
    'migrate': ('relocate, move, wander, journey', 'settle, stay, remain'),
    'milestone': ('breakthrough, landmark, turning point', 'routine, setback'),
    'mimic': ('imitate, copy, simulate, mirror', 'originate, create, invent'),
    'minimize': ('curtail, reduce, downplay, diminish', 'maximize, exaggerate, inflate'),
    'miracle': ('wonder, marvel, phenomenon, sensation', 'natural event, routine'),
    'mischief': ('trouble, nuisance, prank, misbehavior', 'obedience, virtue, order'),
    'miserable': ('wretched, unhappy, distressed, sad', 'happy, cheerful, fortunate'),
    'mislead': ('delude, deceive, misinform, betray', 'guide, enlighten, direct'),
    'mitigate': ('alleviate, ease, soothe, lessen', 'aggravate, worsen, intensify'),
    'modify': ('alter, adapt, adjust, revise', 'maintain, preserve, keep'),
    'momentous': ('historic, significant, vital, monumental', 'trivial, negligible, minor'),
    'monopoly': ('exclusive control, cartel, dominance', 'competition, distribution'),
    'monotonous': ('dull, tedious, repetitive, boring', 'lively, varied, exciting'),
    'morality': ('ethics, righteousness, virtue, integrity', 'immorality, sin, corruption'),
    'motive': ('incentive, impulse, reason, trigger', 'deterrent, prevention'),
    'motivate': ('inspire, stimulate, propel, encourage', 'discourage, depress, deter'),
    'multitude': ('crowd, mass, myriad, host', 'handful, scarcity, few'),
    'mundane': ('ordinary, routine, worldly, boring', 'extraordinary, heavenly, spiritual'),
    'mutual': ('reciprocal, shared, collaborative, common', 'unilateral, one-sided, separate'),
    'naive': ('innocent, credulous, gullible, simple', 'sophisticated, shrewd, worldly'),
    'narrative': ('story, tale, chronicle, account', 'fact sheet, statistic'),
    'nascent': ('emerging, budding, developing, beginning', 'mature, dying, senile'),
    'neglect': ('ignore, disregard, overlook, abandon', 'cherish, care for, attend'),
    'negotiate': ('bargain, arrange, confer, settle', 'dictate, impose, refuse'),
    'neutral': ('impartial, unbiased, indifferent, fair', 'partisan, biased, partial'),
    'noble': ('magnificent, grand, elevated, aristocratic', 'ignoble, base, humble'),
    'notable': ('distinguished, striking, remarkable, famous', 'ordinary, obscure, mediocre'),
    'notion': ('concept, idea, view, impression', 'reality, fact, certainty'),
    'notorious': ('infamous, disreputable, scandalous', 'renowned, famous, celebrated'),
    'novel': ('innovative, original, unprecedented, story', 'traditional, trite, stale'),
    'nurture': ('foster, rear, nourish, cultivate', 'neglect, harm, abandon'),
    'objective': ('unbiased, impartial, aim, goal', 'subjective, partial, biased'),
    'oblige': ('compel, force, require, assist', 'excuse, release, exempt'),
    'obscure': ('vague, dim, unknown, conceal', 'clear, famous, bright'),
    'obstacle': ('barrier, hurdle, impediment, handicap', 'aid, catalyst, gateway'),
    'obtain': ('acquire, gain, secure, achieve', 'lose, forfeit, give up'),
    'obvious': ('evident, clear, apparent, manifest', 'obscure, subtle, hidden'),
    'odd': ('strange, peculiar, eccentric, leftover', 'even, normal, ordinary'),
    'offend': ('insult, displease, transgress, outrage', 'please, delight, flatter'),
    'omit': ('exclude, skip, neglect, drop', 'include, insert, add'),
    'opponent': ('adversary, rival, competitor, foe', 'ally, partner, teammate'),
    'opportunist': ('speculator, exploiter, schemer', 'idealist, altruist'),
    'opportunity': ('chance, opening, occasion, prospect', 'obstacle, hindrance, loss'),
    'oppose': ('resist, contest, defy, challenge', 'support, advocate, back'),
    'optimistic': ('hopeful, positive, confident, cheerful', 'pessimistic, gloomy, hopeless'),
    'opulent': ('luxurious, wealthy, rich, lavish', 'poor, destitute, meager'),
    'originate': ('derive, stem, arise, emanate', 'terminate, end, vanish'),
    'orthodox': ('conventional, standard, customary, traditional', 'unorthodox, radical, heretical'),
    'oscillate': ('swing, vibrate, fluctuate, waver', 'stabilize, remain, freeze'),
    'outbreak': ('eruption, outburst, explosion, burst', 'containment, peace, lull'),
    'outcome': ('result, consequence, effect, aftermath', 'cause, origin, start'),
    'outlaw': ('ban, prohibit, criminal, fugitive', 'legalize, permit, authorize'),
    'outlook': ('perspective, view, forecast, horizon', 'blindness, retrospect'),
    'output': ('production, yield, creation, result', 'input, intake, consumption'),
    'outrage': ('infuriate, scandalize, fury, indignity', 'appease, delight, calm'),
    'outset': ('start, beginning, inception, origin', 'conclusion, end, finale'),
    'outweigh': ('surpass, exceed, override, top', 'fall short, lag behind'),
    'overcome': ('conquer, defeat, master, surmount', 'succumb, yield, fail'),
    'overflow': ('spill over, flood, submerge, inundate', 'dry up, drain, deplete'),
    'overlook': ('ignore, miss, disregard, forgive', 'notice, observe, inspect'),
    'overseas': ('abroad, foreign, international', 'domestic, local, native'),
    'overshadow': ('darken, obscure, eclipse, surpass', 'highlight, emphasize, brighten'),
    'overt': ('open, unconcealed, manifest, explicit', 'covert, hidden, secret'),
    'overwhelm': ('crush, overpower, inundate, engulf', 'underwhelm, succumb'),
    'pace': ('speed, tempo, stride, rate', 'standstill, pause, stagnation'),
    'painstaking': ('meticulous, thorough, diligent, scrupulous', 'careless, slapdash, negligent'),
    'paradox': ('contradiction, anomaly, puzzle, riddle', 'axiom, certainty, fact'),
    'parallel': ('similar, corresponding, aligned, twin', 'divergent, perpendicular, opposite'),
    'paralyze': ('immobilize, cripple, freeze, disable', 'energize, animate, activate'),
    'paramount': ('supreme, chief, dominant, primary', 'minor, secondary, trivial'),
    'partial': ('biased, incomplete, partisan, prejudiced', 'impartial, complete, total'),
    'particle': ('speck, fragment, atom, bit', 'whole, mass, totality'),
    'particular': ('specific, distinct, fastidious, fussy', 'general, universal, ordinary'),
    'passion': ('enthusiasm, ardour, zeal, emotion', 'apathy, indifference, coldness'),
    'passive': ('submissive, compliant, inactive, inert', 'active, dynamic, aggressive'),
    'patient': ('tolerant, enduring, calm, invalid', 'impatient, restless, agitated'),
    'patriotic': ('nationalistic, loyal, devoted', 'traitorous, disloyal'),
    'patron': ('sponsor, backer, customer, benefactor', 'beggar, client, rival'),
    'peak': ('zenith, pinnacle, summit, apex', 'nadir, bottom, base'),
    'peculiar': ('strange, eccentric, unique, distinct', 'normal, typical, conventional'),
    'pedestrian': ('ordinary, dull, walker, passerby', 'extraordinary, driver, flyer'),
    'penetrate': ('pierce, permeate, infiltrate, fathom', 'repel, bounce off, withdraw'),
    'perceive': ('discern, notice, comprehend, observe', 'miss, overlook, ignore'),
    'perennial': ('continual, enduring, persistent, constant', 'ephemeral, temporary, seasonal'),
    'perfect': ('flawless, ideal, consummate, refine', 'flawed, defective, corrupt'),
    'perform': ('execute, enact, fulfill, achieve', 'fail, neglect, abandon'),
    'peril': ('hazard, jeopardy, danger, risk', 'safety, security, sanctuary'),
    'periodic': ('regular, cyclical, recurring, recurrent', 'continuous, constant, random'),
    'perish': ('die, expire, decay, vanish', 'survive, flourish, live'),
    'permanent': ('enduring, lasting, eternal, perpetual', 'temporary, transient, ephemeral'),
    'permeate': ('saturate, penetrate, pervade, diffuse', 'drain, isolate, seal'),
    'perpetual': ('endless, continuous, everlasting, ceaseless', 'intermittent, temporary, brief'),
    'perplex': ('baffle, confound, puzzle, mystify', 'clarify, enlighten, explain'),
    'persist': ('continue, endure, persevere, linger', 'quit, cease, abandon'),
    'perspective': ('viewpoint, outlook, context, angle', 'narrowness, myopia'),
    'persuade': ('convince, coax, sway, induce', 'dissuade, deter, discourage'),
    'pertain': ('relate, belong, refer, apply', 'disconnect, separate'),
    'pessimistic': ('gloomy, cynical, defeatist, hopeless', 'optimistic, hopeful, confident'),
    'phenomenon': ('occurrence, marvel, event, sensation', 'routine, normality'),
    'pinnacle': ('peak, apex, zenith, summit', 'nadir, bottom, trough'),
    'pioneer': ('innovator, trailblazer, groundbreaker, lead', 'follower, imitator'),
    'pitfall': ('trap, hazard, snag, danger', 'advantage, safe path'),
    'pivotal': ('crucial, vital, central, critical', 'minor, secondary, peripheral'),
    'plausible': ('credible, believable, reasonable, likely', 'implausible, incredible, absurd'),
    'plunge': ('drop, plummet, dive, descend', 'soar, rise, ascend'),
    'poisonous': ('toxic, venomous, deadly, noxious', 'harmless, nontoxic, healthy'),
    'polarize': ('divide, split, alienate, sever', 'unite, merge, reconcile'),
    'ponder': ('contemplate, meditate, reflect, muse', 'ignore, disregard, overlook'),
    'portable': ('movable, compact, handy, light', 'immobile, heavy, stationary'),
    'portray': ('depict, describe, represent, characterize', 'misrepresent, distort, disguise'),
    'positive': ('optimistic, affirmative, constructive, sure', 'negative, cynical, doubtful'),
    'potential': ('possible, latent, capability, prospect', 'impossible, actual, realized'),
    'practical': ('pragmatic, feasible, useful, functional', 'impractical, theoretical, absurd'),
    'precaution': ('safeguard, preventive measure, care', 'carelessness, negligence, hazard'),
    'precede': ('lead, antecede, foreshadow, prefix', 'follow, succeed, ensue'),
    'precedent': ('model, standard, benchmark, paradigm', 'anomaly, innovation'),
    'precious': ('valuable, priceless, treasured, rare', 'worthless, cheap, common'),
    'precise': ('exact, accurate, strict, meticulous', 'vague, imprecise, sloppy'),
    'preclude': ('prevent, exclude, eliminate, impede', 'allow, facilitate, permit'),
    'predict': ('forecast, prophesy, anticipate, foresee', 'record, remember, verify'),
    'predominant': ('dominant, prevalent, primary, ruling', 'minor, secondary, subordinate'),
    'prejudice': ('bias, preconception, intolerance, bigotry', 'fairness, tolerance, justice'),
    'preliminary': ('introductory, prior, preparatory, initial', 'final, concluding, ultimate'),
    'premise': ('assumption, hypothesis, foundation, basis', 'conclusion, result'),
    'premium': ('bonus, superior, luxury, choice', 'inferior, penalty, poor'),
    'prescribe': ('dictate, ordain, advise, assign', 'prohibit, ban, abolish'),
    'preserve': ('conserve, maintain, protect, guard', 'destroy, ruin, waste'),
    'prestige': ('reputation, status, renown, honor', 'disgrace, obscurity, shame'),
    'presume': ('assume, suppose, deduce, infer', 'prove, verify, know'),
    'prevail': ('triumph, dominate, exist, overcome', 'fail, collapse, lose'),
    'prevalent': ('widespread, pervasive, dominant, common', 'rare, scarce, isolated'),
    'prevent': ('impede, hinder, avert, inhibit', 'allow, cause, facilitate'),
    'primary': ('fundamental, chief, prime, initial', 'secondary, subordinate, minor'),
    'primitive': ('ancient, crude, rudimentary, raw', 'civilized, modern, advanced'),
    'principal': ('main, chief, vital, head', 'subordinate, secondary, accessory'),
    'principle': ('doctrine, precept, rule, axiom', 'compromise, flexibility'),
    'prior': ('earlier, preceding, antecedent, former', 'subsequent, later, following'),
    'priority': ('precedence, preference, urgency, lead', 'unimportance, triviality'),
    'pristine': ('pure, untouched, immaculate, fresh', 'polluted, corrupted, soiled'),
    'privilege': ('honor, advantage, right, perk', 'disadvantage, handicap, burden'),
    'probable': ('likely, plausible, expected, feasible', 'improbable, unlikely, impossible'),
    'probe': ('investigate, explore, examine, scrutiny', 'ignore, overlook, neglect'),
    'proceed': ('advance, continue, progress, forward', 'retreat, halt, stop'),
    'proclaim': ('announce, declare, herald, broadcast', 'conceal, hide, suppress'),
    'procure': ('obtain, acquire, secure, gain', 'lose, forfeit, surrender'),
    'productive': ('fruitful, prolific, fertile, efficient', 'unproductive, barren, futile'),
    'profound': ('deep, insightful, intense, scholarly', 'superficial, shallow, trivial'),
    'prohibit': ('ban, forbid, disallow, interdict', 'allow, permit, authorize'),
    'prolong': ('extend, lengthen, protract, delay', 'shorten, curtail, abbreviate'),
    'prominent': ('distinguished, eminent, noticeable, salient', 'obscure, hidden, common'),
    'promote': ('advance, boost, champion, foster', 'demote, hinder, suppress'),
    'prompt': ('punctual, quick, trigger, provoke', 'delayed, slow, sluggish'),
    'prone': ('susceptible, vulnerable, liable, inclined', 'immune, resistant, upright'),
    'propel': ('drive, thrust, push, motivate', 'halt, impede, restrain'),
    'proper': ('appropriate, fitting, decent, decorous', 'improper, inappropriate, rude'),
    'proponent': ('advocate, champion, supporter, backer', 'opponent, critic, antagonist'),
    'proportion': ('ratio, balance, segment, fraction', 'disproportion, imbalance'),
    'prospect': ('outlook, potential, vista, possibility', 'hopelessness, retrospect'),
    'prosper': ('thrive, flourish, succeed, bloom', 'decline, fail, wither'),
    'protect': ('guard, defend, shield, shelter', 'endanger, harm, abandon'),
    'protest': ('object, remonstrate, complain, rebel', 'accept, approve, comply'),
    'protocol': ('procedure, code, convention, treaty', 'chaos, informality, breach'),
    'prototype': ('model, blueprint, archetype, original', 'copy, replica, clone'),
    'provide': ('furnish, supply, endow, cater', 'withhold, deny, deprive'),
    'provoke': ('arouse, instigate, incite, trigger', 'calm, soothe, appease'),
    'prudent': ('cautious, discreet, sensible, wise', 'reckless, rash, foolish'),
    'punctual': ('prompt, timely, on time, exact', 'tardy, late, delayed'),
    'purchase': ('buy, procure, acquire, grasp', 'sell, forfeit, vend'),
    'purify': ('cleanse, refine, filter, sanitize', 'contaminate, pollute, corrupt'),
    'pursue': ('chase, seek, stalk, follow', 'abandon, avoid, flee'),
    'puzzle': ('baffle, confound, mystery, riddle', 'clarify, explain, solve'),
    'qualified': ('competent, capable, licensed, eligible', 'unqualified, inept, unfit'),
    'qualitative': ('characteristic, descriptive, subjective', 'quantitative, numerical'),
    'quantitative': ('numerical, measurable, statistical', 'qualitative, descriptive'),
    'quench': ('extinguish, satisfy, slake, douse', 'ignite, inflame, arouse'),
    'quest': ('search, journey, mission, inquiry', 'abandonment, surrender'),
    'radiant': ('luminous, glowing, splendid, cheerful', 'dim, dark, gloomy'),
    'radical': ('drastic, extreme, revolutionary, fundamental', 'conservative, moderate, conventional'),
    'random': ('arbitrary, haphazard, chance, erratic', 'systematic, deliberate, planned'),
    'rapid': ('swift, fast, speedy, prompt', 'slow, sluggish, gradual'),
    'rational': ('reasonable, logical, sensible, sane', 'irrational, illogical, absurd'),
    'ravage': ('devastate, ruin, destroy, plunder', 'repair, preserve, build'),
    'raw': ('unprocessed, crude, harsh, fresh', 'refined, cooked, processed'),
    'react': ('respond, reply, counteract, recoil', 'ignore, remain passive'),
    'reap': ('harvest, gather, gain, obtain', 'sow, plant, lose'),
    'reassure': ('comfort, console, encourage, hearten', 'intimidate, frighten, discourage'),
    'rebel': ('mutineer, insurgent, defy, resist', 'conform, obey, submit'),
    'rebuke': ('reprimand, scold, admonish, chide', 'praise, commend, applaud'),
    'recede': ('retreat, withdraw, subside, ebb', 'advance, approach, grow'),
    'receptive': ('open-minded, welcoming, responsive', 'stubborn, resistant, closed'),
    'recession': ('downturn, slump, decline, contraction', 'boom, expansion, prosperity'),
    'reciprocal': ('mutual, bilateral, return, complementary', 'unilateral, one-sided'),
    'reckless': ('rash, careless, irresponsible, heedless', 'cautious, prudent, careful'),
    'reconcile': ('harmonize, reunite, settle, resolve', 'alienate, divide, conflict'),
    'recruit': ('enlist, draft, hire, mobilize', 'discharge, dismiss, fire'),
    'rectify': ('correct, amend, remedy, adjust', 'damage, worsen, falsify'),
    'recur': ('repeat, reoccur, persist, return', 'stop, end, cease'),
    'recycle': ('reprocess, reuse, reclaim, salvage', 'waste, discard, destroy'),
    'redundant': ('superfluous, surplus, repetitive, excess', 'essential, scarce, necessary'),
    'refine': ('purify, polish, improve, distill', 'corrupt, crude, pollute'),
    'reflect': ('mirror, ponder, contemplate, echo', 'ignore, absorb, disregard'),
    'refrain': ('abstain, avoid, desist, hold back', 'indulge, pursue, continue'),
    'refresh': ('invigorate, restore, revitalize, renew', 'exhaust, tire, drain'),
    'refuge': ('sanctuary, haven, shelter, asylum', 'peril, danger, trap'),
    'refund': ('reimburse, repay, restore, rebate', 'charge, fine, bill'),
    'refute': ('disprove, rebut, contradict, debunk', 'confirm, verify, corroborate'),
    'regardless': ('despite, notwithstanding, heedless', 'mindful, heedful, attentive'),
    'regenerate': ('revive, renew, restore, rebuild', 'degenerate, decay, rot'),
    'regulate': ('control, govern, adjust, standardize', 'disrupt, deregulate, disorder'),
    'rehabilitate': ('restore, reform, recover, reintegrate', 'corrupt, destroy, demote'),
    'reinforce': ('strengthen, fortify, boost, bolster', 'weaken, undermine, sap'),
    'reinstate': ('restore, return, reestablish, reinstall', 'dismiss, suspend, oust'),
    'reiterate': ('repeat, restate, emphasize, recapitulate', 'retract, cancel, deny'),
    'rejoice': ('celebrate, delight, exult, cheer', 'mourn, grieve, weep'),
    'relapse': ('worsen, regress, deteriorate, slip back', 'recover, improve, progress'),
    'relate': ('connect, link, narrate, associate', 'separate, isolate, detach'),
    'relax': ('unwind, loosen, ease, calm', 'tense, tighten, agitate'),
    'relay': ('transmit, convey, broadcast, communicate', 'withhold, suppress, retain'),
    'release': ('free, liberate, publish, discharge', 'detain, conceal, imprison'),
    'relentless': ('unyielding, persistent, ruthless, fierce', 'lenient, gentle, merciful'),
    'relevant': ('pertinent, applicable, germane, related', 'irrelevant, extraneous, unrelated'),
    'reliable': ('trustworthy, dependable, credible, sound', 'unreliable, deceitful, dubious'),
    'relief': ('ease, comfort, respite, assistance', 'agony, distress, burden'),
    'relinquish': ('surrender, abandon, yield, renounce', 'retain, keep, claim'),
    'reluctance': ('unwillingness, hesitation, aversion', 'eagerness, willingness, zeal'),
    'rely': ('depend, trust, count on, lean', 'distrust, doubt, suspect'),
    'remain': ('stay, linger, abide, persist', 'leave, depart, vanish'),
    'remarkable': ('extraordinary, striking, notable, stellar', 'ordinary, mediocre, common'),
    'remedy': ('cure, treatment, fix, solution', 'disease, poison, harm'),
    'remnant': ('residue, remainder, scrap, fragment', 'whole, entirety, aggregate'),
    'remote': ('distant, far, isolated, aloof', 'near, close, adjacent'),
    'render': ('make, cause, deliver, provide', 'withhold, prevent, retain'),
    'renovate': ('renew, restore, revamp, modernize', 'demolish, neglect, ruin'),
    'renown': ('fame, prestige, glory, reputation', 'obscurity, infamy, shame'),
    'repel': ('repulse, drive away, disgust, resist', 'attract, welcome, invite'),
    'repent': ('regret, atone, lament, deplore', 'persevere, boast, rejoice'),
    'replace': ('substitute, supplant, supersede, swap', 'retain, keep, maintain'),
    'replenish': ('refill, restore, renew, recharge', 'deplete, drain, exhaust'),
    'replicate': ('duplicate, reproduce, clone, repeat', 'originate, create, invent'),
    'represent': ('symbolize, depict, embody, stand for', 'misrepresent, distort, falsify'),
    'repress': ('suppress, subdue, stifle, restrain', 'express, liberate, encourage'),
    'reproduce': ('replicate, copy, breed, generate', 'destroy, exterminate, kill'),
    'reproach': ('blame, scold, rebuke, reprimand', 'praise, flatter, commend'),
    'repudiate': ('reject, renounce, disown, deny', 'embrace, accept, adopt'),
    'repulsive': ('disgusting, hideous, offensive, loathsome', 'attractive, appealing, charming'),
    'reputation': ('renown, prestige, standing, name', 'infamy, obscurity, shame'),
    'require': ('demand, need, necessitate, stipulate', 'waive, excuse, offer'),
    'rescue': ('save, liberate, retrieve, salvage', 'abandon, endanger, sacrifice'),
    'resemble': ('mirror, look like, echo, favor', 'differ, contrast, clash'),
    'resent': ('begrudge, dislike, grudge, detest', 'appreciate, welcome, forgive'),
    'reserve': ('withhold, retain, set aside, book', 'release, squander, display'),
    'reservoir': ('basin, storehouse, pool, supply', 'drain, void, vacuum'),
    'reside': ('dwell, inhabit, abide, stay', 'roam, depart, leave'),
    'residue': ('remnant, leftover, deposit, silt', 'whole, bulk, entirety'),
    'resign': ('abdicate, quit, step down, yield', 'maintain, retain, assume'),
    'resilient': ('elastic, tough, sturdy, adaptable', 'fragile, brittle, weak'),
    'resist': ('withstand, oppose, defy, combat', 'submit, yield, succumb'),
    'resolute': ('determined, steadfast, firm, unwavering', 'indecisive, hesitant, wavering'),
    'resolve': ('determine, solve, settle, clarify', 'waver, complicate, prolong'),
    'resort': ('turn to, apply, haunt, retreat', 'avoid, shun, reject'),
    'resource': ('asset, supply, fund, wealth', 'scarcity, poverty, dearth'),
    'respect': ('esteem, honor, value, regard', 'disdain, scorn, insult'),
    'respective': ('individual, particular, personal, own', 'collective, combined, universal'),
    'respond': ('reply, answer, react, retort', 'ignore, disregard, overlook'),
    'responsible': ('accountable, answerable, liable, ethical', 'irresponsible, reckless, careless'),
    'restore': ('rebuild, recover, renew, reinstate', 'destroy, damage, abolish'),
    'restrain': ('curb, inhibit, restrict, suppress', 'unleash, liberate, encourage'),
    'restrict': ('limit, constrain, confine, bound', 'expand, free, broaden'),
    'resume': ('restart, continue, reopen, proceed', 'suspend, interrupt, halt'),
    'retain': ('preserve, keep, hold, remember', 'discard, lose, surrender'),
    'retaliate': ('revenge, strike back, avenge, retort', 'forgive, pardon, condone'),
    'retard': ('slow down, delay, impede, hinder', 'accelerate, hasten, foster'),
    'retract': ('withdraw, cancel, recant, revoke', 'assert, affirm, confirm'),
    'retreat': ('withdraw, recoil, flee, sanctuary', 'advance, attack, charge'),
    'retrieve': ('recover, fetch, regain, salvage', 'lose, forfeit, abandon'),
    'retrospect': ('review, recollection, hindsight', 'prospect, forecast, future'),
    'reveal': ('disclose, unveil, expose, manifest', 'conceal, hide, mask'),
    'revenge': ('vengeance, retaliation, retribution', 'forgiveness, mercy, pardon'),
    'revenue': ('income, earnings, proceeds, profit', 'expenditure, loss, expense'),
    'reverse': ('invert, overturn, opposite, backward', 'maintain, confirm, advance'),
    'review': ('evaluate, inspect, survey, revise', 'ignore, overlook, skip'),
    'revise': ('alter, modify, correct, amend', 'leave unchanged, finalize'),
    'revive': ('resuscitate, rejuvenate, restore, renew', 'kill, extinguish, perish'),
    'revoke': ('cancel, repeal, annul, rescind', 'enact, enforce, confirm'),
    'revolt': ('rebel, mutiny, disgust, riot', 'submit, comply, obey'),
    'revolution': ('transformation, uprising, overthrow, cycle', 'stagnation, conservation, status quo'),
    'reward': ('recompense, bonus, prize, bounty', 'penalty, fine, punishment'),
    'riddle': ('puzzle, enigma, mystery, conundrum', 'solution, answer, fact'),
    'ridicule': ('mock, deride, taunt, scoff', 'praise, honor, respect'),
    'rigid': ('stiff, unyielding, rigorous, strict', 'flexible, pliable, lenient'),
    'rigorous': ('strict, demanding, precise, meticulous', 'sloppy, lenient, careless'),
    'rival': ('competitor, adversary, match, contend', 'ally, teammate, partner'),
    'robust': ('vigorous, sturdy, tough, strong', 'feeble, fragile, delicate'),
    'rotate': ('revolve, spin, alternate, turn', 'remain static, freeze'),
    'routine': ('habit, custom, standard, regular', 'novelty, exception, anomaly'),
    'rudimentary': ('basic, elementary, primitive, primary', 'advanced, complex, refined'),
    'ruin': ('devastate, spoil, destroy, wreckage', 'construct, restore, preserve'),
    'rumor': ('hearsay, gossip, speculation', 'fact, truth, certainty'),
    'rupture': ('break, burst, split, fracture', 'heal, mend, join'),
    'rural': ('country, pastoral, rustic, agricultural', 'urban, metropolitan, city'),
    'sacred': ('holy, divine, consecrated, spiritual', 'secular, profane, worldly'),
    'sacrifice': ('surrender, offer, forfeit, give up', 'acquire, profit, hoard'),
    'safeguard': ('protect, shield, defend, precaution', 'endanger, hazard, jeopardize'),
    'salient': ('prominent, striking, noticeable, distinct', 'unnoticeable, hidden, minor'),
    'salvage': ('rescue, recover, save, reclaim', 'abandon, forfeit, scrap'),
    'sanction': ('authorize, approve, penalty, boycott', 'prohibit, ban, veto'),
    'sarcastic': ('ironic, mocking, cynical, caustic', 'sincere, polite, kind'),
    'saturate': ('soak, drench, permeate, steep', 'drain, dehydrate, dry'),
    'scale': ('range, proportion, ascend, weigh', 'descend, decline'),
    'scan': ('examine, survey, scrutinize, glance', 'ignore, overlook'),
    'scarce': ('sparse, deficient, rare, meager', 'abundant, plentiful, copious'),
    'scatter': ('disperse, distribute, sprinkle, diffuse', 'gather, collect, hoard'),
    'scenario': ('situation, framework, scheme, plot', 'reality, fact'),
    'sceptical': ('doubtful, distrustful, questioning, cynical', 'credulous, trusting, certain'),
    'scheme': ('plan, plot, strategy, design', 'accident, chance'),
    'scholarly': ('academic, erudite, intellectual, learned', 'illiterate, crude, vulgar'),
    'scope': ('range, extent, horizon, domain', 'narrowness, limitation'),
    'scorn': ('despise, disdain, mock, sneer', 'respect, admire, esteem'),
    'scramble': ('climb, struggle, jostle, mix', 'stroll, order, calm'),
    'scrap': ('fragment, discard, piece, cancel', 'preserve, keep, whole'),
    'scrutinize': ('examine, inspect, audit, dissect', 'glance, overlook, ignore'),
    'sculpture': ('statue, carving, monument, craft', 'painting, text'),
    'seasoned': ('experienced, veteran, mature, skilled', 'inexperienced, green, rookie'),
    'seclude': ('isolate, hide, quarantine, conceal', 'integrate, expose, mingle'),
    'secondary': ('subordinate, minor, auxiliary, second', 'primary, chief, prime'),
    'secretive': ('covert, stealthy, furtive, guarded', 'open, transparent, frank'),
    'secure': ('safe, firm, acquire, fasten', 'insecure, vulnerable, loose'),
    'sedentary': ('inactive, stationary, desk-bound, seated', 'active, mobile, dynamic'),
    'segment': ('portion, division, part, piece', 'whole, entirety, aggregate'),
    'segregate': ('separate, isolate, divide, disconnect', 'integrate, unite, mix'),
    'seldom': ('rarely, infrequently, scarcely', 'frequently, often, regularly'),
    'selective': ('discerning, particular, fastidious, careful', 'indiscriminate, careless, general'),
    'sensation': ('feeling, perception, marvel, uproar', 'numbness, apathy, routine'),
    'sensible': ('reasonable, rational, practical, wise', 'foolish, absurd, irrational'),
    'sensitive': ('receptive, touchy, delicate, tender', 'insensitive, callous, numb'),
    'sentiment': ('emotion, opinion, attitude, feeling', 'indifference, fact, apathy'),
    'sequence': ('order, succession, chain, series', 'chaos, randomness, disorder'),
    'serene': ('calm, placid, tranquil, peaceful', 'turbulent, stormy, agitated'),
    'severe': ('harsh, strict, intense, rigorous', 'mild, gentle, lenient'),
    'shallow': ('superficial, trivial, slight, flat', 'deep, profound, insightful'),
    'shatter': ('break, smash, destroy, demolish', 'mend, repair, assemble'),
    'sheer': ('pure, absolute, steep, transparent', 'moderate, partial, gradual'),
    'shelter': ('protect, harbor, sanctuary, haven', 'expose, evict, abandon'),
    'shift': ('move, change, alter, transfer', 'remain, fix, stabilize'),
    'shortcoming': ('defect, flaw, drawback, weakness', 'strength, virtue, merit'),
    'shrewd': ('astute, sharp, clever, perceptive', 'naive, foolish, gullible'),
    'shrink': ('contract, decrease, diminish, recoil', 'expand, enlarge, grow'),
    'shun': ('avoid, evade, reject, boycott', 'embrace, welcome, seek'),
    'sibling': ('brother, sister, kin', 'stranger, alien'),
    'signal': ('sign, indicate, announce, gesture', 'conceal, hide, silence'),
    'significant': ('important, notable, momentous, substantial', 'trivial, minor, negligible'),
    'simplify': ('clarify, streamline, demystify, reduce', 'complicate, confuse, entangle'),
    'simulate': ('mimic, reproduce, model, imitate', 'originate, create, discover'),
    'simultaneous': ('coincident, concurrent, synchronized', 'sequential, asynchronous, apart'),
    'sincere': ('honest, genuine, heartfelt, frank', 'hypocritical, fake, deceitful'),
    'singular': ('unique, remarkable, extraordinary, sole', 'ordinary, common, plural'),
    'skeptical': ('doubtful, cynical, questioning, suspicious', 'believing, trusting, credulous'),
    'skillful': ('adept, proficient, expert, masterly', 'clumsy, inept, awkward'),
    'slender': ('slim, lean, slight, modest', 'fat, broad, bulky'),
    'slight': ('minor, slim, modest, insult', 'major, massive, substantial'),
    'slippery': ('slick, treacherous, elusive, tricky', 'rough, firm, stable'),
    'slope': ('incline, slant, pitch, gradient', 'level, plateau, flat'),
    'sluggish': ('slow, lethargic, lazy, stagnant', 'brisk, energetic, quick'),
    'soar': ('rise, ascend, surge, skyrocket', 'plunge, plummet, sink'),
    'sober': ('serious, grave, sensible, temperate', 'drunk, frivolous, reckless'),
    'socialize': ('mingle, interact, civilize, train', 'isolate, alienate, seclude'),
    'solitary': ('lone, isolated, single, companionless', 'social, gregarious, accompanied'),
    'somber': ('gloomy, dismal, grave, dark', 'cheerful, joyful, bright'),
    'sophisticated': ('refined, intricate, worldly, advanced', 'crude, primitive, naive'),
    'sound': ('solid, rational, healthy, noise', 'flawed, unsound, sick'),
    'sour': ('acid, tart, bitter, unpleasant', 'sweet, pleasant, cordial'),
    'sovereign': ('ruler, monarch, independent, supreme', 'dependent, subject, subordinate'),
    'spacious': ('roomy, capacious, expansive, broad', 'cramped, narrow, crowded'),
    'spark': ('ignite, trigger, kindle, flash', 'extinguish, smother, douse'),
    'sparse': ('meager, scarce, scattered, thin', 'dense, thick, abundant'),
    'spatial': ('dimensional, geographical, territorial', 'temporal, nonspatial'),
    'specialize': ('focus, concentrate, dedicate, narrow', 'generalize, diversify'),
    'specific': ('particular, explicit, definite, distinct', 'general, vague, broad'),
    'specimen': ('sample, example, instance, model', 'whole, population'),
    'spectacular': ('magnificent, stunning, dramatic, grand', 'ordinary, plain, unimpressive'),
    'speculate': ('ponder, meditate, gamble, conjecture', 'prove, verify, know'),
    'sphere': ('domain, realm, globe, field', 'flatland, void'),
    'spin': ('rotate, revolve, whirl, narrate', 'halt, stop, freeze'),
    'splendid': ('magnificent, glorious, brilliant, superb', 'poor, drab, awful'),
    'split': ('divide, tear, cleave, rupture', 'unite, join, connect'),
    'spoil': ('ruin, corrupt, pamper, plunder', 'repair, enhance, discipline'),
    'spontaneous': ('unplanned, impulsive, natural, automatic', 'deliberate, rehearsed, calculated'),
    'sporadic': ('intermittent, occasional, scattered, patchy', 'constant, continuous, steady'),
    'spotlight': ('highlight, feature, focus, illuminate', 'ignore, obscure, shadow'),
    'sprout': ('grow, bud, germinate, spring', 'wither, decay, die'),
    'spurious': ('fake, counterfeit, false, bogus', 'genuine, authentic, valid'),
    'squander': ('waste, lavish, deplete, dissipate', 'conserve, save, treasure'),
    'stagnant': ('inactive, sluggish, still, foul', 'flowing, dynamic, active'),
    'stake': ('hazard, risk, wager, interest', 'guarantee, certainty'),
    'stamina': ('endurance, vigor, resilience, strength', 'fragility, weakness, fatigue'),
    'standard': ('benchmark, criterion, normal, metric', 'anomaly, deviation'),
    'standpoint': ('perspective, angle, viewpoint, stance', 'objectivity, vacuum'),
    'startle': ('shock, surprise, frighten, alarm', 'soothe, calm, pacify'),
    'starve': ('famish, deprive, hunger, crave', 'feed, nourish, gorge'),
    'static': ('fixed, stationary, unchanged, stable', 'dynamic, active, moving'),
    'stationary': ('motionless, fixed, static, frozen', 'mobile, moving, traveling'),
    'statistic': ('figure, metric, data, index', 'guess, anecdote'),
    'status': ('rank, position, prestige, condition', 'insignificance, obscurity'),
    'statute': ('law, regulation, decree, enactment', 'anarchy, chaos'),
    'steadfast': ('loyal, resolute, unwavering, staunch', 'wavering, fickle, disloyal'),
    'steady': ('constant, firm, stable, uninterrupted', 'erratic, unstable, unsteady'),
    'steep': ('sheer, precipitous, abrupt, soak', 'gentle, gradual, flat'),
    'steer': ('guide, direct, pilot, navigate', 'abandon, drift, misdirect'),
    'stem': ('originate, derive, stalk, halt', 'end, terminate, cause'),
    'sterile': ('barren, infertile, aseptic, antiseptic', 'fertile, productive, infected'),
    'stimulate': ('provoke, motivate, inspire, arouse', 'depress, stifle, suppress'),
    'stipulate': ('specify, demand, require, contract', 'waive, omit, ignore'),
    'straightforward': ('direct, frank, simple, honest', 'complicated, evasive, tricky'),
    'strain': ('stress, tension, exert, pressure', 'relaxation, ease, relief'),
    'strategy': ('tactic, plan, policy, approach', 'improvisation, chance'),
    'stray': ('wander, deviate, roam, lost', 'stay, remain, conform'),
    'strenuous': ('demanding, exhausting, arduous, vigorous', 'effortless, easy, light'),
    'stress': ('emphasize, highlight, tension, pressure', 'downplay, relax, ease'),
    'stride': ('step, pace, progress, advance', 'stumble, retreat, halt'),
    'striking': ('prominent, remarkable, noticeable, stunning', 'ordinary, plain, unremarkable'),
    'strive': ('struggle, endeavor, seek, fight', 'quit, surrender, yield'),
    'stubborn': ('obstinate, rigid, headstrong, unyielding', 'flexible, compliant, docile'),
    'stumble': ('trip, falter, hesitate, flounder', 'stride, glide, advance'),
    'subdue': ('conquer, tame, suppress, defeat', 'unleash, liberate, incite'),
    'subjective': ('personal, biased, emotional, individual', 'objective, impartial, fair'),
    'submerge': ('immerse, plunge, sink, flood', 'surface, emerge, rise'),
    'submit': ('yield, comply, surrender, present', 'resist, rebel, defy'),
    'subordinate': ('inferior, junior, secondary, dependent', 'superior, chief, dominant'),
    'subscribe': ('support, sign, endorse, contribute', 'reject, unsubscribe, protest'),
    'subsequent': ('following, later, ensuing, consequent', 'previous, prior, preceding'),
    'subside': ('diminish, abate, decline, recede', 'surge, escalate, rise'),
    'subsidy': ('grant, aid, allowance, support', 'tax, penalty, tariff'),
    'substance': ('matter, core, essence, reality', 'emptiness, shadow, void'),
    'substantial': ('significant, solid, immense, real', 'trivial, meager, flimsy'),
    'substantiate': ('verify, confirm, corroborate, validate', 'refute, disprove, invalidate'),
    'substitute': ('replace, surrogate, alternate, swap', 'keep, retain, maintain'),
    'subtle': ('delicate, elusive, refined, understated', 'obvious, crude, blatant'),
    'subtract': ('deduct, remove, decrease, diminish', 'add, increase, append'),
    'subvert': ('overthrow, undermine, destabilize, corrupt', 'uphold, support, stabilize'),
    'succeed': ('triumph, thrive, follow, ensue', 'fail, collapse, precede'),
    'succinct': ('concise, brief, compact, terse', 'verbose, wordy, rambling'),
    'succumb': ('yield, surrender, perish, collapse', 'resist, withstand, conquer'),
    'suffice': ('satisfy, serve, answer, do', 'fall short, fail, lack'),
    'sufficient': ('enough, adequate, ample, plenty', 'insufficient, deficient, meager'),
    'summarize': ('recap, condense, abridge, outline', 'expand, elaborate, prolong'),
    'summit': ('peak, zenith, apex, conference', 'nadir, bottom, base'),
    'superb': ('splendid, excellent, magnificent, sublime', 'poor, terrible, mediocre'),
    'superficial': ('shallow, surface, trivial, cosmetic', 'profound, deep, thorough'),
    'superior': ('greater, higher, better, senior', 'inferior, lower, poorer'),
    'supersede': ('replace, supplant, succeed, override', 'retain, keep, preserve'),
    'supplement': ('complement, augment, add, addition', 'diminish, subtract, deplete'),
    'suppress': ('subdue, repress, crush, conceal', 'express, encourage, liberate'),
    'supreme': ('highest, ultimate, sovereign, paramount', 'inferior, lowly, minor'),
    'surge': ('gush, rush, swell, escalate', 'recede, decline, plunge'),
    'surpass': ('exceed, outdo, transcend, excel', 'fall behind, lag, fail'),
    'surplus': ('excess, overage, residue, extra', 'deficit, shortage, lack'),
    'surrender': ('yield, capitulate, concede, submit', 'resist, conquer, withstand'),
    'survey': ('inspect, investigate, overview, probe', 'ignore, overlook, glance'),
    'susceptible': ('vulnerable, prone, sensitive, liable', 'immune, resistant, safe'),
    'suspect': ('distrust, doubt, question, speculate', 'trust, believe, confirm'),
    'suspend': ('pause, interrupt, postpone, hang', 'resume, continue, enact'),
    'suspicious': ('doubtful, skeptical, wary, dubious', 'trusting, confident, certain'),
    'sustain': ('maintain, support, endure, uphold', 'abandon, collapse, discontinue'),
    'sustainable': ('viable, eco-friendly, maintainable, durable', 'unsustainable, wasteful, harmful'),
    'swift': ('rapid, quick, prompt, fast', 'slow, sluggish, delayed'),
    'symbol': ('emblem, token, mark, sign', 'reality, substance'),
    'symmetry': ('balance, proportion, harmony, alignment', 'asymmetry, imbalance, discord'),
    'sympathy': ('compassion, empathy, pity, kindness', 'indifference, callousness, cruelty'),
    'symptom': ('sign, indication, manifestation, mark', 'cure, cause'),
    'synchronize': ('align, coordinate, match, harmonize', 'desynchronize, conflict, clash'),
    'synergy': ('collaboration, combined effort, harmony', 'conflict, opposition, friction'),
    'synthetic': ('artificial, man-made, fabricated, faux', 'natural, genuine, organic'),
    'systematic': ('methodical, organized, structured, orderly', 'random, chaotic, disorganized'),
    'tacit': ('implicit, unspoken, unexpressed, silent', 'explicit, voiced, declared'),
    'tackle': ('confront, address, handle, grapple', 'evade, avoid, ignore'),
    'tactics': ('strategy, maneuver, scheme, methods', 'blunder, chaos'),
    'taint': ('contaminate, corrupt, spoil, blemish', 'purify, clean, sanctify'),
    'tangible': ('concrete, touchable, physical, palpable', 'intangible, abstract, elusive'),
    'taper': ('narrow, diminish, decrease, fade', 'widen, expand, broaden'),
    'tarnish': ('blemish, stain, dim, discredit', 'polish, brighten, honor'),
    'tedious': ('monotonous, boring, dull, tiresome', 'exciting, lively, engaging'),
    'temper': ('moderate, soften, disposition, mood', 'aggravate, inflame, worsen'),
    'temperate': ('moderate, mild, restrained, calm', 'extreme, intemperate, violent'),
    'temporary': ('transient, fleeting, provisional, brief', 'permanent, eternal, lasting'),
    'tempt': ('entice, lure, seduce, invite', 'deter, repel, discourage'),
    'tenacious': ('persistent, stubborn, determined, resolute', 'yielding, weak, vacillating'),
    'tendency': ('trend, inclination, propensity, bias', 'aversion, opposition'),
    'tentative': ('provisional, hesitant, cautious, trial', 'definite, certain, final'),
    'terminate': ('conclude, stop, finish, cancel', 'commence, begin, start'),
    'terrible': ('dreadful, awful, horrible, severe', 'wonderful, pleasant, great'),
    'terrific': ('fabulous, tremendous, superb, grand', 'terrible, awful, mediocre'),
    'testify': ('witness, attest, declare, verify', 'refute, deny, conceal'),
    'thorough': ('exhaustive, complete, meticulous, rigorous', 'superficial, sloppy, partial'),
    'threaten': ('menace, endanger, intimidate, jeopardize', 'protect, comfort, reassure'),
    'thrive': ('prosper, flourish, bloom, succeed', 'wither, decline, decay'),
    'timid': ('fearful, shy, bashful, cowardly', 'bold, brave, daring'),
    'tiny': ('minute, microscopic, small, miniature', 'huge, enormous, gigantic'),
    'tolerate': ('endure, bear, permit, countenance', 'reject, forbid, ban'),
    'toxic': ('poisonous, venomous, noxious, lethal', 'nontoxic, healthy, healing'),
    'tractable': ('docile, compliant, manageable, yielding', 'stubborn, intractable, defiant'),
    'traditional': ('conventional, customary, standard, classic', 'modern, novel, revolutionary'),
    'tragedy': ('calamity, catastrophe, disaster, grief', 'comedy, triumph, joy'),
    'trait': ('characteristic, feature, attribute, quality', 'whole, totality'),
    'tranquil': ('serene, peaceful, calm, placid', 'turbulent, stormy, noisy'),
    'transcend': ('surpass, exceed, outdo, excel', 'fall short, lag behind'),
    'transform': ('convert, alter, revolutionize, metamorphose', 'preserve, maintain, retain'),
    'transient': ('fleeting, temporary, passing, brief', 'permanent, enduring, timeless'),
    'transparent': ('clear, lucid, candid, see-through', 'opaque, ambiguous, obscure'),
    'treasure': ('cherish, value, prize, hoard', 'discard, neglect, squander'),
    'tremendous': ('immense, colossal, gigantic, huge', 'tiny, trivial, slight'),
    'trigger': ('spark, initiate, provoke, prompt', 'halt, suppress, prevent'),
    'triumph': ('victory, conquest, succeed, rejoice', 'defeat, failure, collapse'),
    'trivial': ('minor, insignificant, petty, negligible', 'crucial, significant, vital'),
    'turbulent': ('chaotic, stormy, violent, restless', 'calm, tranquil, serene'),
    'ultimate': ('final, conclusive, supreme, paramount', 'initial, primary, starting'),
    'unanimous': ('agreed, undivided, accordant, joint', 'divided, conflicting, discordant'),
    'unavoidable': ('inevitable, inescapable, destined', 'avoidable, preventable'),
    'unbiased': ('impartial, objective, fair, neutral', 'biased, partial, prejudiced'),
    'uncertain': ('doubtful, dubious, unpredictable, vague', 'certain, definite, confident'),
    'unconditional': ('absolute, total, categorical, complete', 'conditional, limited, restricted'),
    'underestimate': ('undervalue, belittle, minimize, misjudge', 'overestimate, exaggerate'),
    'undergo': ('endure, experience, sustain, bear', 'avoid, escape, bypass'),
    'underlie': ('support, ground, fund, form foundation', 'overlie, surface'),
    'underline': ('emphasize, highlight, stress, underscore', 'downplay, ignore, overlook'),
    'undermine': ('weaken, subvert, sabotage, impair', 'strengthen, reinforce, support'),
    'underpin': ('support, bolster, fortify, reinforce', 'weaken, undermine, shake'),
    'undertake': ('embark, assume, attempt, tackle', 'abandon, avoid, quit'),
    'unequivocal': ('unambiguous, clear, explicit, direct', 'ambiguous, equivocal, vague'),
    'unfavorable': ('adverse, hostile, disadvantageous, bad', 'favorable, beneficial, positive'),
    'uniform': ('consistent, homogeneous, identical, even', 'varied, diverse, irregular'),
    'unique': ('singular, sole, matchless, distinct', 'common, ordinary, ubiquitous'),
    'unite': ('join, merge, fuse, combine', 'divide, separate, split'),
    'universal': ('global, general, all-inclusive, cosmic', 'local, specific, narrow'),
    'unprecedented': ('novel, groundbreaking, unrivaled, historic', 'routine, common, traditional'),
    'unveil': ('reveal, uncover, disclose, introduce', 'conceal, hide, mask'),
    'upbeat': ('optimistic, cheerful, positive, buoyed', 'gloomy, pessimistic, depressed'),
    'upgrade': ('elevate, improve, promote, enhance', 'downgrade, demote, degrade'),
    'uphold': ('defend, support, maintain, sustain', 'overturn, abandon, subvert'),
    'upright': ('vertical, honest, righteous, moral', 'crooked, corrupt, prone'),
    'uprising': ('rebellion, revolt, mutiny, insurrection', 'surrender, obedience, peace'),
    'urgent': ('pressing, crucial, emergency, immediate', 'trivial, routine, delayable'),
    'utilize': ('employ, use, leverage, exploit', 'waste, neglect, discard'),
    'utmost': ('maximum, supreme, extreme, highest', 'least, minimum, slight'),
    'vacant': ('empty, unoccupied, blank, void', 'occupied, full, crowded'),
    'vague': ('indefinite, ambiguous, obscure, hazy', 'clear, precise, explicit'),
    'valid': ('legitimate, sound, lawful, confirmed', 'invalid, null, void'),
    'vanish': ('disappear, fade, dissolve, evaporate', 'appear, emerge, surface'),
    'variable': ('shifting, volatile, erratic, changing', 'constant, steady, fixed'),
    'variance': ('difference, discrepancy, divergence, variation', 'agreement, consistency, harmony'),
    'various': ('diverse, varied, manifold, assorted', 'uniform, identical, same'),
    'vast': ('immense, huge, broad, boundless', 'tiny, narrow, limited'),
    'venerable': ('respected, revered, honored, esteemed', 'disreputable, base, despised'),
    'venture': ('undertaking, risk, gamble, attempt', 'certainty, security, safety'),
    'verdict': ('judgment, decision, ruling, finding', 'indecision, accusation'),
    'verify': ('confirm, corroborate, substantiate, prove', 'refute, debunk, disprove'),
    'versatile': ('adaptable, flexible, all-around, handy', 'rigid, specialized, limited'),
    'vertical': ('upright, perpendicular, erect, sheer', 'horizontal, flat, level'),
    'veto': ('reject, prohibit, disallow, ban', 'approve, sanction, endorse'),
    'viable': ('feasible, practicable, workable, liveable', 'infeasible, impossible, dead'),
    'vibrant': ('energetic, lively, dynamic, vivid', 'dull, sluggish, lifeless'),
    'vicious': ('malicious, savage, cruel, spiteful', 'kind, gentle, virtuous'),
    'vigorous': ('energetic, robust, forceful, dynamic', 'feeble, weak, sluggish'),
    'vindicate': ('justify, clear, acquit, exonerate', 'convict, condemn, blame'),
    'violate': ('breach, infringe, transgress, break', 'obey, respect, observe'),
    'virtue': ('morality, goodness, merit, advantage', 'vice, sin, defect'),
    'visible': ('apparent, noticeable, clear, perceptible', 'invisible, hidden, obscure'),
    'vision': ('insight, foresight, sight, dream', 'blindness, ignorance'),
    'vital': ('crucial, essential, fundamental, lively', 'trivial, minor, dead'),
    'vivid': ('graphic, distinct, colorful, bright', 'vague, dull, dim'),
    'vocal': ('outspoken, voiced, expressive, spoken', 'silent, mute, reticent'),
    'void': ('empty, null, vacant, vacuum', 'full, valid, crowded'),
    'volatile': ('erratic, explosive, unstable, fickle', 'stable, calm, steady'),
    'volume': ('quantity, bulk, capacity, book', 'scarcity, shortage'),
    'voluntary': ('willing, optional, spontaneous, unpaid', 'mandatory, forced, coerced'),
    'vulnerable': ('susceptible, fragile, exposed, defenseless', 'invulnerable, resilient, safe'),
    'warrant': ('justify, authorize, guarantee, permit', 'forbid, disallow, deny'),
    'widespread': ('pervasive, universal, common, extensive', 'isolated, localized, rare'),
    'withdraw': ('retreat, pull out, retract, revoke', 'advance, insert, deposit'),
    'wither': ('decay, shrivel, fade, decline', 'flourish, bloom, thrive'),
    'withhold': ('retain, repress, refuse, suppress', 'grant, provide, yield'),
    'withstand': ('endure, resist, tolerate, survive', 'surrender, collapse, succumb'),
    'witness': ('observe, testify, spectator, evidence', 'ignore, deny, conceal'),
    'wreck': ('destroy, ruin, shatter, wreckage', 'repair, preserve, build'),
    'yield': ('surrender, produce, generate, succumb', 'resist, withstand, consume'),
    'zeal': ('passion, enthusiasm, ardour, fervor', 'apathy, indifference, coldness'),
    'zenith': ('peak, apex, pinnacle, summit', 'nadir, bottom, base')
}

def enrich_synonyms_and_tags():
    with open(WORDS_PATH, 'r', encoding='utf-8') as f:
        doc = json.load(f)
    words = doc['words']
    active_words = [w for w in words if w.get('active') is not False]
    
    syn_count = 0
    tag_count = 0
    
    for w in active_words:
        wd = w['word'].lower().strip()
        
        # 1. Apply Synonym/Antonym network
        if wd in SYN_ANT_PAIRS:
            syn, ant = SYN_ANT_PAIRS[wd]
            if not w.get('synonyms'):
                w['synonyms'] = syn
                syn_count += 1
            if not w.get('antonyms'):
                w['antonyms'] = ant
                
        # 2. Apply Exam Question Type Tag
        exam_tags = []
        if wd in EXAM_TAGS['attitude']:
            exam_tags.append('阅读态度词')
        if wd in EXAM_TAGS['cloze_logic']:
            exam_tags.append('完形逻辑词')
        if wd in EXAM_TAGS['translation']:
            exam_tags.append('翻译抽象词')
        if wd in EXAM_TAGS['writing']:
            exam_tags.append('写作黄金词')
            
        if w.get('tier') == '核心高频' and not exam_tags:
            exam_tags.append('真题高频核心')
        elif w.get('tier') == '高频重点' and not exam_tags:
            exam_tags.append('考研重点必背')
            
        if exam_tags:
            w['exam_tag'] = ' · '.join(exam_tags)
            tag_count += 1
            
    doc['DATA_VERSION'] = "5894-v9-exam-enriched"
    doc['data_version'] = "5894-v9-exam-enriched"
    
    with open(WORDS_PATH, 'w', encoding='utf-8') as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        
    print(f"Enriched {syn_count} words with new synonyms/antonyms.")
    print(f"Enriched {tag_count} words with exam question type tags (exam_tag).")

if __name__ == '__main__':
    enrich_synonyms_and_tags()
